In [ ]:
!pip -q install transformers pandas
!git clone -q https://github.com/aetting/lm-diagnostics.git

In [ ]:
import os, re, torch, numpy as np, pandas as pd
from transformers import BertTokenizer, BertForMaskedLM

REPO = "/content/lm-diagnostics"
SIMP_PATH = f"{REPO}/datasets/NEG-136/NEG-136-SIMP.tsv"
NAT_PATH  = f"{REPO}/datasets/NEG-136/NEG-136-NAT.tsv"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)

simp_raw = pd.read_csv(SIMP_PATH, sep="\t")
nat_raw  = pd.read_csv(NAT_PATH, sep="\t")

print("SIMP:", simp_raw.shape)  # (18, 5)
print("NAT :", nat_raw.shape)   # (16, 6)
display(simp_raw.head())
display(nat_raw.head())

device: cuda
SIMP: (18, 5)
NAT : (16, 6)

   item         context_aff             context_neg target_aff target_neg
0     0   A trout is (a|an)   A trout is not (a|an)       fish       tool
1     1  A salmon is (a|an)  A salmon is not (a|an)       fish     flower
2     2    An ant is (a|an)    An ant is not (a|an)     insect  vegetable
3     3     A bee is (a|an)     A bee is not (a|an)     insect   building
4     4   A robin is (a|an)   A robin is not (a|an)       bird       tree

,item,context_aff,context_neg,target_aff,target_neg,licensing
0,0,"With proper equipment, scuba-diving is very","With proper equipment, scuba-diving isn't very",safe,dangerous,Y
1,1,Traveling in Baghdad is very,Traveling in Baghdad isn't very,dangerous,safe,Y
2,2,"In moderation, drinking red wine is","In moderation, drinking red wine isn't",good,bad,Y
3,3,Drinking tap water in developing countries is ...,Drinking tap water in developing countries isn...,dangerous,safe,Y
4,4,Secondhand furniture is very,Secondhand furniture isn't very,cheap,expensive,Y

In [ ]:
def process_negsimp(path):
    rows = []
    df = pd.read_csv(path, sep="\t")

    for _, r in df.iterrows():
        affsent = re.sub(r" \(.+\)", "", r["context_aff"])
        negsent = re.sub(r" \(.+\)", "", r["context_neg"])
        afftgt = r["target_aff"].strip()
        negtgt = r["target_neg"].strip()

        for sent, tgt, cond in [
            (affsent, afftgt, "TA"),
            (negsent, afftgt, "FN"),
            (affsent, negtgt, "FA"),
            (negsent, negtgt, "TN"),
        ]:
            det = "an" if re.match(r"[aeiou]", tgt) else "a"
            context = f"{sent} {det} [MASK]"
            expected = afftgt if cond in ("TA", "FA") else negtgt
            rows.append({
                "item": str(r["item"]),
                "cond": cond,
                "context": context,
                "target": tgt,
                "expected": expected,
            })
    return pd.DataFrame(rows)


def process_negnat(path):
    rows = []
    df = pd.read_csv(path, sep="\t")

    for _, r in df.iterrows():
        affsent = r["context_aff"].strip()
        negsent = r["context_neg"].strip()
        afftgt = r["target_aff"].strip()
        negtgt = r["target_neg"].strip()

        for sent, tgt, cond in [
            (affsent, afftgt, "TA"),
            (negsent, afftgt, "FN"),
            (affsent, negtgt, "FA"),
            (negsent, negtgt, "TN"),
        ]:
            context = f"{sent} [MASK]"   # IMPORTANT: no a/an here
            expected = afftgt if cond in ("TA", "FA") else negtgt
            rows.append({
                "item": str(r["item"]),
                "cond": cond,
                "context": context,
                "target": tgt,
                "expected": expected,
                "licensing": r["licensing"],  # Y = natural; N = less natural
            })
    return pd.DataFrame(rows)

simp = process_negsimp(SIMP_PATH)
nat = process_negnat(NAT_PATH)

assert len(simp) == 18 * 4
assert len(nat) == 16 * 4
assert set(simp.cond) == {"TA","FN","FA","TN"}
assert set(nat.cond) == {"TA","FN","FA","TN"}

display(simp.head(8))
display(nat.head(8))

  item cond                   context  target expected
0    0   TA       A trout is a [MASK]    fish     fish
1    0   FN   A trout is not a [MASK]    fish     tool
2    0   FA       A trout is a [MASK]    tool     fish
3    0   TN   A trout is not a [MASK]    tool     tool
4    1   TA      A salmon is a [MASK]    fish     fish
5    1   FN  A salmon is not a [MASK]    fish   flower
6    1   FA      A salmon is a [MASK]  flower     fish
7    1   TN  A salmon is not a [MASK]  flower   flower

,item,cond,context,target,expected,licensing
0,0,TA,"With proper equipment, scuba-diving is very [M...",safe,safe,Y
1,0,FN,"With proper equipment, scuba-diving isn't very...",safe,dangerous,Y
2,0,FA,"With proper equipment, scuba-diving is very [M...",dangerous,safe,Y
3,0,TN,"With proper equipment, scuba-diving isn't very...",dangerous,dangerous,Y
4,1,TA,Traveling in Baghdad is very [MASK],dangerous,dangerous,Y
5,1,FN,Traveling in Baghdad isn't very [MASK],dangerous,safe,Y
6,1,FA,Traveling in Baghdad is very [MASK],safe,dangerous,Y
7,1,TN,Traveling in Baghdad isn't very [MASK],safe,safe,Y

In [ ]:
def load_bert(name):
    tok = BertTokenizer.from_pretrained(name)
    model = BertForMaskedLM.from_pretrained(name).to(device)
    model.eval()
    return tok, model

tok_base, bert_base = load_bert("bert-base-uncased")
tok_large, bert_large = load_bert("bert-large-uncased")
print("Models loaded.")

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  440MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

[transformers] BertForMaskedLM LOAD REPORT from: bert-base-uncased
Key                         | Status     |  |
----------------------------+------------+--+-
cls.seq_relationship.bias   | UNEXPECTED |  |
cls.seq_relationship.weight | UNEXPECTED |  |
bert.pooler.dense.bias      | UNEXPECTED |  |
bert.pooler.dense.weight    | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.34GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/394 [00:00<?, ?it/s]

[transformers] BertForMaskedLM LOAD REPORT from: bert-large-uncased
Key                         | Status     |  |
----------------------------+------------+--+-
cls.seq_relationship.bias   | UNEXPECTED |  |
cls.seq_relationship.weight | UNEXPECTED |  |
bert.pooler.dense.bias      | UNEXPECTED |  |
bert.pooler.dense.weight    | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Models loaded.

In [ ]:
def prep_input(sentence, tokenizer):
    text = ["[CLS]"] + sentence.strip().split()
    if text[-1] != ".":
        text.append(".")
    text.append("[SEP]")

    tokenized = tokenizer.tokenize(" ".join(text))
    mask_positions = [i for i, t in enumerate(tokenized) if t == "[MASK]"]
    assert len(mask_positions) == 1, (sentence, tokenized)

    ids = tokenizer.convert_tokens_to_ids(tokenized)
    input_ids = torch.tensor([ids], device=device)
    return input_ids, mask_positions[0], tokenized


@torch.inference_mode()
def score_dataframe(df, model, tokenizer, topk=5):
    out = df.copy()
    target_probs, top_tokens, top_probs = [], [], []

    for _, row in out.iterrows():
        input_ids, mi, toks = prep_input(row["context"], tokenizer)
        logits = model(input_ids=input_ids).logits[0, mi]
        probs = torch.softmax(logits, dim=-1)

        # NEG-136 targets are intended to be single BERT vocabulary tokens.
        target = row["target"]
        pieces = tokenizer.tokenize(target)
        assert len(pieces) == 1 and pieces[0] == target, (target, pieces)
        target_id = tokenizer.convert_tokens_to_ids(target)
        target_probs.append(probs[target_id].item())

        vals, inds = torch.topk(probs, k=topk)
        top_tokens.append(tokenizer.convert_ids_to_tokens(inds.tolist()))
        top_probs.append(vals.detach().cpu().tolist())

    out["target_prob"] = target_probs
    out["top_tokens"] = top_tokens
    out["top_probs"] = top_probs
    return out

In [ ]:
# Sanity check: this should look like "[CLS] a robin is a [MASK] . [SEP]"
example = simp.query("item == '4' and cond == 'TA'").iloc[0]
_, mi, toks = prep_input(example.context, tok_large)
print(example.context)
print(toks)
print("mask index:", mi)

A robin is a [MASK]
['[CLS]', 'a', 'robin', 'is', 'a', '[MASK]', '.', '[SEP]']
mask index: 5

In [ ]:
simp_base  = score_dataframe(simp, bert_base,  tok_base,  topk=5)
simp_large = score_dataframe(simp, bert_large, tok_large, topk=5)
nat_base   = score_dataframe(nat,  bert_base,  tok_base,  topk=5)
nat_large  = score_dataframe(nat,  bert_large, tok_large, topk=5)

print("Scoring complete.")

Scoring complete.

In [ ]:
def simp_accuracy(scored, k):
    ta = scored[scored.cond == "TA"].copy()
    hits = [
        int(row.expected in row.top_tokens[:k])
        for _, row in ta.iterrows()
    ]
    return 100 * np.mean(hits), sum(hits), len(hits)

table11 = pd.DataFrame([
    ["BERT Base",  *simp_accuracy(simp_base, 1), *simp_accuracy(simp_base, 5)],
    ["BERT Large", *simp_accuracy(simp_large, 1), *simp_accuracy(simp_large, 5)],
], columns=["Model", "k1_pct", "k1_correct", "k1_n", "k5_pct", "k5_correct", "k5_n"])

display(table11)

print("Paper target:")
print("BERT Base : k=1 38.9%, k=5 100%")
print("BERT Large: k=1 44.4%, k=5 100%")

        Model     k1_pct  k1_correct  k1_n  k5_pct  k5_correct  k5_n
0   BERT Base  38.888889           7    18   100.0          18    18
1  BERT Large  44.444444           8    18   100.0          18    18

Paper target:
BERT Base : k=1 38.9%, k=5 100%
BERT Large: k=1 44.4%, k=5 100%

In [ ]:
def wide_probs(scored):
    return (
        scored.pivot(index="item", columns="cond", values="target_prob")
              .reset_index()
    )

def neg_sensitivity(scored, threshold=None):
    w = wide_probs(scored)

    aff_diff = w["TA"] - w["FA"]
    neg_diff = w["TN"] - w["FN"]

    if threshold is None:
        aff_hit = aff_diff > 0
        neg_hit = neg_diff > 0
    else:
        aff_hit = aff_diff > threshold
        neg_hit = neg_diff > threshold

    return {
        "Affirmative": 100 * aff_hit.mean(),
        "Negative": 100 * neg_hit.mean(),
        "Aff_correct": int(aff_hit.sum()),
        "Neg_correct": int(neg_hit.sum()),
        "n": len(w),
    }

table12 = pd.DataFrame([
    {"Model": "BERT Base",  **neg_sensitivity(simp_base)},
    {"Model": "BERT Large", **neg_sensitivity(simp_large)},
])
display(table12)

print("Paper target: both models = 100% affirmative, 0% negative")

# The paper also discusses a 0.01 probability-difference threshold.
table12_threshold = pd.DataFrame([
    {"Model": "BERT Base",  **neg_sensitivity(simp_base, threshold=.01)},
    {"Model": "BERT Large", **neg_sensitivity(simp_large, threshold=.01)},
])
display(table12_threshold)

        Model  Affirmative  Negative  Aff_correct  Neg_correct   n
0   BERT Base        100.0       0.0           18            0  18
1  BERT Large        100.0       0.0           18            0  18

Paper target: both models = 100% affirmative, 0% negative

        Model  Affirmative  Negative  Aff_correct  Neg_correct   n
0   BERT Base    94.444444       0.0           17            0  18
1  BERT Large   100.000000       0.0           18            0  18

In [ ]:
def nat_table14(scored):
    meta = scored[["item", "licensing"]].drop_duplicates("item")
    w = wide_probs(scored).merge(meta, on="item", how="left")

    result = {}
    for lic, label in [("Y", "NT"), ("N", "LN")]:
        d = w[w.licensing == lic]
        result[f"Aff. {label}"] = 100 * (d["TA"] > d["FA"]).mean()
        result[f"Neg. {label}"] = 100 * (d["TN"] > d["FN"]).mean()
    return result

table14 = pd.DataFrame([
    {"Model": "BERT Base",  **nat_table14(nat_base)},
    {"Model": "BERT Large", **nat_table14(nat_large)},
])
table14 = table14[["Model", "Aff. NT", "Neg. NT", "Aff. LN", "Neg. LN"]]
display(table14)

print("Paper target:")
print("BERT Base : 62.5, 87.5, 75.0, 0.0")
print("BERT Large: 75.0, 100.0, 75.0, 0.0")

        Model  Aff. NT  Neg. NT  Aff. LN  Neg. LN
0   BERT Base     62.5     87.5     75.0      0.0
1  BERT Large     75.0    100.0     75.0      0.0

Paper target:
BERT Base : 62.5, 87.5, 75.0, 0.0
BERT Large: 75.0, 100.0, 75.0, 0.0

In [ ]:
def show_context_predictions(scored, contexts):
    rows = []
    for context in contexts:
        match = scored[scored.context == context]
        if len(match):
            r = match.iloc[0]
            rows.append({
                "Context": context.replace("[MASK]", "____"),
                "BERT Large predictions": ", ".join(r.top_tokens[:5])
            })
    return pd.DataFrame(rows)

table13_contexts = [
    "A robin is a [MASK]",
    "A daisy is a [MASK]",
    "A hammer is a [MASK]",
    "A hammer is an [MASK]",
    "A robin is not a [MASK]",
    "A daisy is not a [MASK]",
    "A hammer is not a [MASK]",
    "A hammer is not an [MASK]",
]

table13 = show_context_predictions(simp_large, table13_contexts)
display(table13)

                   Context                         BERT Large predictions
0        A robin is a ____            bird, robin, person, hunter, pigeon
1        A daisy is a ____               daisy, rose, flower, berry, tree
2       A hammer is a ____             hammer, tool, weapon, nail, device
3      A hammer is an ____  object, instrument, axe, implement, explosive
4    A robin is not a ____                 robin, bird, penguin, man, fly
5    A daisy is not a ____              daisy, rose, flower, lily, cherry
6   A hammer is not a ____                hammer, weapon, tool, gun, rock
7  A hammer is not an ____      object, instrument, axe, animal, artifact

In [ ]:
table15_contexts = [
    "Most smokers find that quitting is very [MASK]",
    "Most smokers find that quitting isn't very [MASK]",
    "A fast food dinner on a first date is very [MASK]",
    "A fast food dinner on a first date isn't very [MASK]",
]

table15 = show_context_predictions(nat_large, table15_contexts)
display(table15)

,Context,BERT Large predictions
0,Most smokers find that quitting is very ____,"difficult, easy, effective, dangerous, hard"
1,Most smokers find that quitting isn't very ____,"effective, easy, attractive, difficult, succes..."
2,A fast food dinner on a first date is very ____,"good, nice, common, romantic, attractive"
3,A fast food dinner on a first date isn't very ...,"nice, good, romantic, appealing, exciting"

In [ ]:
def audit(scored):
    w = wide_probs(scored)
    w["TA>FA"] = w["TA"] > w["FA"]
    w["TN>FN"] = w["TN"] > w["FN"]
    w["TA-FA"] = w["TA"] - w["FA"]
    w["TN-FN"] = w["TN"] - w["FN"]
    return w

print("SIMP — BERT Base")
display(audit(simp_base))

print("SIMP — BERT Large")
display(audit(simp_large))

print("NAT — BERT Base")
display(audit(nat_base))

print("NAT — BERT Large")
display(audit(nat_large))

SIMP — BERT Base

cond,item,FA,FN,TA,TN,TA>FA,TN>FN,TA-FA,TN-FN
0,0,0.000454,0.282158,0.458702,7.007256e-05,True,False,0.458248,-0.282088
1,1,0.000294,0.372949,0.468620,7.392465e-05,True,False,0.468326,-0.372875
2,10,0.000044,0.007566,0.001668,6.144525e-04,True,False,0.001624,-0.006952
3,11,0.000435,0.012711,0.031981,3.654529e-04,True,False,0.031546,-0.012346
4,12,0.000578,0.177014,0.325408,4.986854e-04,True,False,0.324830,-0.176515
5,13,0.000004,0.022030,0.159117,4.140205e-06,True,False,0.159113,-0.022025
6,14,0.000095,0.238066,0.243470,1.194748e-04,True,False,0.243375,-0.237947
7,15,0.000016,0.103839,0.239107,4.882722e-06,True,False,0.239090,-0.103835
8,16,0.000005,0.002389,0.018337,3.913319e-07,True,False,0.018333,-0.002389
9,17,0.000120,0.013464,0.055227,1.260634e-05,True,False,0.055107,-0.013451
10,2,0.000369,0.009920,0.023876,6.548225e-04,True,False,0.023507,-0.009265
11,3,0.000738,0.612482,0.726103,8.571031e-05,True,False,0.725365,-0.612396
12,4,0.005804,0.096690,0.315533,2.640250e-03,True,False,0.309729,-0.094050
13,5,0.000021,0.535142,0.545084,1.468437e-05,True,False,0.545063,-0.535127
14,6,0.000042,0.927698,0.797508,4.915193e-05,True,False,0.797466,-0.927649
15,7,0.000095,0.542941,0.770262,2.896631e-04,True,False,0.770167,-0.542652
16,8,0.002200,0.303401,0.511275,1.144714e-03,True,False,0.509075,-0.302256
17,9,0.000197,0.072219,0.054946,6.657573e-04,True,False,0.054749,-0.071553

SIMP — BERT Large

cond,item,FA,FN,TA,TN,TA>FA,TN>FN,TA-FA,TN-FN
0,0,0.000055,0.539623,0.825476,0.000059,True,False,0.825421,-0.539563
1,1,0.000037,0.350676,0.597984,0.000058,True,False,0.597947,-0.350618
2,10,0.004687,0.015102,0.040064,0.003551,True,False,0.035377,-0.011551
3,11,0.000148,0.002650,0.041610,0.000089,True,False,0.041462,-0.002561
4,12,0.001689,0.095098,0.151806,0.002493,True,False,0.150117,-0.092605
5,13,0.000065,0.052297,0.500279,0.000082,True,False,0.500214,-0.052215
6,14,0.000148,0.066921,0.167242,0.000285,True,False,0.167094,-0.066637
7,15,0.000003,0.036160,0.029305,0.000007,True,False,0.029302,-0.036153
8,16,0.000004,0.008605,0.031087,0.000008,True,False,0.031083,-0.008597
9,17,0.000003,0.080459,0.217257,0.000033,True,False,0.217254,-0.080427
10,2,0.004742,0.085352,0.321126,0.002807,True,False,0.316385,-0.082545
11,3,0.000198,0.358430,0.491372,0.000052,True,False,0.491174,-0.358378
12,4,0.009511,0.087829,0.247797,0.002373,True,False,0.238286,-0.085456
13,5,0.000006,0.462497,0.580487,0.000002,True,False,0.580480,-0.462495
14,6,0.000183,0.774649,0.744313,0.000085,True,False,0.744129,-0.774564
15,7,0.000428,0.209651,0.522395,0.000156,True,False,0.521968,-0.209495
16,8,0.002698,0.058658,0.080181,0.001701,True,False,0.077483,-0.056958
17,9,0.001616,0.011399,0.086995,0.000451,True,False,0.085379,-0.010948

NAT — BERT Base

cond,item,FA,FN,TA,TN,TA>FA,TN>FN,TA-FA,TN-FN
0,0,0.038337,0.235215,0.109465,0.061657,True,False,0.071128,-0.173558
1,1,0.001107,0.014538,0.024116,0.039021,True,True,0.023009,0.024483
2,10,0.000092,0.159419,0.036679,0.010483,True,False,0.036587,-0.148936
3,11,0.000594,0.062366,0.002340,0.006485,True,False,0.001747,-0.055881
4,12,0.001750,0.009430,0.007406,0.000855,True,False,0.005655,-0.008575
5,13,0.000499,0.002088,0.000259,0.000066,False,False,-0.000240,-0.002023
6,14,0.002797,0.175657,0.245660,0.002639,True,False,0.242863,-0.173018
7,15,0.001028,0.015686,0.025153,0.000950,True,False,0.024126,-0.014736
8,2,0.000123,0.012109,0.000409,0.027839,True,True,0.000286,0.015730
9,3,0.023134,0.003575,0.004445,0.177035,False,True,-0.018689,0.173460
10,4,0.242264,0.014924,0.030158,0.080950,False,True,-0.212106,0.066026
11,5,0.049715,0.021924,0.218186,0.120850,True,True,0.168471,0.098926
12,6,0.000063,0.000039,0.000070,0.000250,True,True,0.000007,0.000211
13,7,0.011733,0.000084,0.003008,0.010720,False,True,-0.008724,0.010635
14,8,0.010563,0.015214,0.001097,0.010070,False,False,-0.009466,-0.005144
15,9,0.002555,0.065769,0.181133,0.025235,True,False,0.178578,-0.040534

NAT — BERT Large

cond,item,FA,FN,TA,TN,TA>FA,TN>FN,TA-FA,TN-FN
0,0,0.150971,0.147417,0.486117,0.384907,True,True,0.335145,0.237490
1,1,0.002638,0.019196,0.180071,0.060117,True,True,0.177433,0.040920
2,10,0.000127,0.221379,0.006098,0.001321,True,False,0.005971,-0.220057
3,11,0.000814,0.010763,0.004963,0.001637,True,False,0.004149,-0.009126
4,12,0.005743,0.090414,0.012966,0.000201,True,False,0.007224,-0.090212
5,13,0.000338,0.005825,0.000118,0.000141,False,False,-0.000221,-0.005684
6,14,0.001726,0.202487,0.532831,0.002655,True,False,0.531106,-0.199832
7,15,0.000551,0.095063,0.015363,0.002058,True,False,0.014812,-0.093004
8,2,0.000110,0.023491,0.001340,0.267007,True,True,0.001230,0.243516
9,3,0.001160,0.002768,0.008258,0.213558,True,True,0.007098,0.210790
10,4,0.274936,0.014287,0.022342,0.024761,False,True,-0.252594,0.010475
11,5,0.066778,0.038530,0.526481,0.117782,True,True,0.459703,0.079251
12,6,0.000029,0.000144,0.000219,0.000240,True,True,0.000190,0.000096
13,7,0.038933,0.000304,0.000188,0.105096,False,True,-0.038746,0.104793
14,8,0.027752,0.014733,0.006038,0.000875,False,False,-0.021714,-0.013858
15,9,0.000705,0.012015,0.341211,0.003446,True,False,0.340505,-0.008569

In [ ]:
# ---- Upload NEG-136-SIMP-BAL.tsv (Colab file picker) ----
BAL_FILENAME = "NEG-136-SIMP-BAL-RARE.tsv"
BAL_PATH = f"/content/{BAL_FILENAME}"

if not os.path.exists(BAL_PATH):          # skip the picker if it's already uploaded
    from google.colab import files
    uploaded = files.upload()             # choose NEG-136-SIMP-BAL.tsv
    BAL_PATH = f"/content/{next(iter(uploaded))}"

bal_raw = pd.read_csv(BAL_PATH, sep="\t")
print("BAL path:", BAL_PATH)
print("BAL:", bal_raw.shape)              # expected (70, 5)
assert list(bal_raw.columns) == list(simp_raw.columns), bal_raw.columns
display(bal_raw.head())

# Balance check: each category should appear equally often as target_aff and as target_neg
display(pd.DataFrame({"as target_aff": bal_raw.target_aff.value_counts(),
                      "as target_neg": bal_raw.target_neg.value_counts()}))

Saving NEG-136-SIMP-BAL-RARE.tsv to NEG-136-SIMP-BAL-RARE.tsv
BAL path: /content/NEG-136-SIMP-BAL-RARE.tsv
BAL: (70, 5)

   item          context_aff              context_neg target_aff target_neg
0     1  A granary is (a|an)  A granary is not (a|an)   building      fruit
1     2   A banana is (a|an)   A banana is not (a|an)      fruit     flower
2     3    A hotel is (a|an)    A hotel is not (a|an)   building       fish
3     4     A moth is (a|an)     A moth is not (a|an)     insect       bird
4     5   A chisel is (a|an)   A chisel is not (a|an)       tool     flower

           as target_aff  as target_neg
bird                   7              7
building               7              7
fish                   7              7
flower                 7              7
fruit                  7              7
insect                 7              7
tool                   7              7
tree                   7              7
vegetable              7              7
vehicle                7              7

In [ ]:

bal = process_negsimp(BAL_PATH)

assert len(bal) == len(bal_raw) * 4
assert set(bal.cond) == {"TA","FN","FA","TN"}

for name, tok in [("base", tok_base), ("large", tok_large)]:
    bad = [t for t in sorted(bal.target.unique()) if tok.tokenize(t) != [t]]
    print(f"{name}: targets that are NOT single tokens -> {bad if bad else 'none'}")

display(bal.head(8))

base: targets that are NOT single tokens -> none
large: targets that are NOT single tokens -> none

  item cond                    context    target  expected
0    1   TA      A granary is a [MASK]  building  building
1    1   FN  A granary is not a [MASK]  building     fruit
2    1   FA      A granary is a [MASK]     fruit  building
3    1   TN  A granary is not a [MASK]     fruit     fruit
4    2   TA       A banana is a [MASK]     fruit     fruit
5    2   FN   A banana is not a [MASK]     fruit    flower
6    2   FA       A banana is a [MASK]    flower     fruit
7    2   TN   A banana is not a [MASK]    flower    flower

In [ ]:

example = bal.query("context == 'A robin is a [MASK]' and cond == 'TA'").iloc[0]
_, mi, toks = prep_input(example.context, tok_large)
print(example.context)
print(toks)
print("mask index:", mi)

A robin is a [MASK]
['[CLS]', 'a', 'robin', 'is', 'a', '[MASK]', '.', '[SEP]']
mask index: 5

In [ ]:
bal_base  = score_dataframe(bal, bert_base,  tok_base,  topk=5)
bal_large = score_dataframe(bal, bert_large, tok_large, topk=5)
print("Scoring complete (BAL).")

Scoring complete (BAL).

In [ ]:

table11_bal = pd.DataFrame([
    ["BERT Base",  *simp_accuracy(bal_base, 1),  *simp_accuracy(bal_base, 5)],
    ["BERT Large", *simp_accuracy(bal_large, 1), *simp_accuracy(bal_large, 5)],
], columns=["Model", "k1_pct", "k1_correct", "k1_n", "k5_pct", "k5_correct", "k5_n"])

print("Table 11 — NEG-136-SIMP-BAL")
display(table11_bal)

Table 11 — NEG-136-SIMP-BAL

        Model     k1_pct  k1_correct  k1_n     k5_pct  k5_correct  k5_n
0   BERT Base  35.714286          25    70  88.571429          62    70
1  BERT Large  55.714286          39    70  97.142857          68    70

In [ ]:

table12_bal = pd.DataFrame([
    {"Model": "BERT Base",  **neg_sensitivity(bal_base)},
    {"Model": "BERT Large", **neg_sensitivity(bal_large)},
])
print("Table 12 — NEG-136-SIMP-BAL")
display(table12_bal)

table12_bal_threshold = pd.DataFrame([
    {"Model": "BERT Base",  **neg_sensitivity(bal_base,  threshold=.01)},
    {"Model": "BERT Large", **neg_sensitivity(bal_large, threshold=.01)},
])
print("Table 12 (threshold 0.01) — NEG-136-SIMP-BAL")
display(table12_bal_threshold)

Table 12 — NEG-136-SIMP-BAL

        Model  Affirmative  Negative  Aff_correct  Neg_correct   n
0   BERT Base   100.000000  1.428571           70            1  70
1  BERT Large    98.571429  1.428571           69            1  70

Table 12 (threshold 0.01) — NEG-136-SIMP-BAL

        Model  Affirmative  Negative  Aff_correct  Neg_correct   n
0   BERT Base    92.857143  1.428571           65            1  70
1  BERT Large    95.714286  1.428571           67            1  70

In [ ]:

table13_bal = show_context_predictions(bal_large, table13_contexts)
print("Table 13 — NEG-136-SIMP-BAL (BERT Large)")
display(table13_bal)

Table 13 — NEG-136-SIMP-BAL (BERT Large)

                   Context                         BERT Large predictions
0        A robin is a ____            bird, robin, person, hunter, pigeon
1        A daisy is a ____               daisy, rose, flower, berry, tree
2       A hammer is a ____             hammer, tool, weapon, nail, device
3      A hammer is an ____  object, instrument, axe, implement, explosive
4    A robin is not a ____                 robin, bird, penguin, man, fly
5    A daisy is not a ____              daisy, rose, flower, lily, cherry
6   A hammer is not a ____                hammer, weapon, tool, gun, rock
7  A hammer is not an ____      object, instrument, axe, animal, artifact

In [ ]:

!pip -q install wordfreq
from wordfreq import zipf_frequency

ETTINGER = {"trout", "salmon", "ant", "bee", "robin", "sparrow", "oak", "pine", "rose",
            "daisy", "carrot", "pea", "hammer", "saw", "car", "truck", "hotel", "house"}

def table13_full(scored, raw, model_name):
    ta = scored[scored.cond == "TA"].set_index("item")
    fn = scored[scored.cond == "FN"].set_index("item")
    rows = []
    for _, r in raw.iterrows():
        item = str(r["item"])
        hyponym = re.match(r"^(?:A|An)\s+(.+?)\s+is\b", r["context_aff"], flags=re.I).group(1).lower()
        cat = r["target_aff"]
        top_aff = ta.loc[item, "top_tokens"][:5]
        top_neg = fn.loc[item, "top_tokens"][:5]
        z = round(zipf_frequency(hyponym, "en"), 2)
        rows.append({
            "Model": model_name,
            "item": int(item),
            "hyponym": hyponym,
            "category": cat,
            "zipf": z,
            "frequency": "rare (<3)" if z < 3 else "not rare",
            "Ettinger": hyponym in ETTINGER,
            "Affirmative context": ta.loc[item, "context"].replace("[MASK]", "____"),
            "Top-5 (affirmative)": ", ".join(top_aff),
            "category in top-5": cat in top_aff,
            "category is top-1": top_aff[0] == cat,
            "Negated context": fn.loc[item, "context"].replace("[MASK]", "____"),
            "Top-5 (negated)": ", ".join(top_neg),
            "category STILL in top-5 after 'not'": cat in top_neg,
        })
    return pd.DataFrame(rows).sort_values("item").reset_index(drop=True)

t13_base  = table13_full(bal_base,  bal_raw, "BERT Base")
t13_large = table13_full(bal_large, bal_raw, "BERT Large")
t13_all   = pd.concat([t13_base, t13_large], ignore_index=True)

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_colwidth", 60)
for name, t in [("BERT Large", t13_large), ("BERT Base", t13_base)]:
    print(f"\nTable 13 — NEG-136-SIMP-BAL-RARE, {name}, all items (n={len(t)})")
    display(t.drop(columns="Model"))


def summarise(t, by=None):
    g = t.groupby(by) if by else t.groupby(lambda _: "all items")
    return g.agg(n=("item", "size"),
                 aff_top5=("category in top-5", "sum"),
                 aff_top1=("category is top-1", "sum"),
                 still_top5_after_not=("category STILL in top-5 after 'not'", "sum"))

for name, t in [("BERT Large", t13_large), ("BERT Base", t13_base)]:
    print(f"\n{name} — overall");            display(summarise(t))
    print(f"{name} — rare vs not rare");      display(summarise(t, "frequency"))
    print(f"{name} — per category");          display(summarise(t, "category"))


fails = t13_all[~t13_all["category in top-5"]]
print("\nItems where the category is NOT in the affirmative top-5:")
display(fails[["Model", "item", "hyponym", "category", "zipf", "frequency", "Top-5 (affirmative)"]])


t13_all.to_csv("table13_full_NEG-136-SIMP-BAL-RARE.csv", index=False)
try:
    from google.colab import files
    files.download("table13_full_NEG-136-SIMP-BAL-RARE.csv")
except ImportError:
    print("Saved table13_full_NEG-136-SIMP-BAL-RARE.csv")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.8/56.8 MB 16.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.1/183.1 kB 19.7 MB/s eta 0:00:00

Table 13 — NEG-136-SIMP-BAL-RARE, BERT Large, all items (n=70)

,item,hyponym,category,zipf,frequency,Ettinger,Affirmative context,Top-5 (affirmative),category in top-5,category is top-1,Negated context,Top-5 (negated),category STILL in top-5 after 'not'
0,1,granary,building,2.57,rare (<3),False,A granary is a ____,"building, warehouse, barn, house, structure",True,True,A granary is not a ____,"building, house, hotel, farm, barn",True
1,2,banana,fruit,4.00,not rare,False,A banana is a ____,"banana, tree, fruit, vegetable, plant",True,False,A banana is not a ____,"banana, vegetable, tree, fruit, peach",True
2,3,hotel,building,4.95,not rare,True,A hotel is a ____,"hotel, resort, building, house, motel",True,False,A hotel is not a ____,"hotel, motel, resort, casino, restaurant",False
3,4,moth,insect,3.50,not rare,False,A moth is an ____,"insect, animal, object, ant, organism",True,True,A moth is not an ____,"animal, insect, object, ant, egg",True
4,5,chisel,tool,2.96,rare (<3),False,A chisel is a ____,"tool, hammer, knife, blade, weapon",True,True,A chisel is not a ____,"tool, knife, hammer, blade, weapon",True
5,6,train,vehicle,4.96,not rare,False,A train is a ____,"train, vehicle, locomotive, car, railroad",True,False,A train is not a ____,"train, car, boat, bus, ship",False
6,7,church,building,5.16,not rare,False,A church is a ____,"church, cathedral, parish, monastery, temple",False,False,A church is not a ____,"church, temple, cathedral, building, monastery",True
7,8,cabbage,vegetable,3.55,not rare,False,A cabbage is a ____,"cabbage, vegetable, carrot, plant, potato",True,False,A cabbage is not a ____,"cabbage, vegetable, carrot, bean, dog",True
8,9,kestrel,bird,2.47,rare (<3),False,A kestrel is a ____,"bird, raven, pigeon, crow, hawk",True,True,A kestrel is not a ____,"bird, raven, butterfly, crow, pigeon",True
9,10,school,building,5.71,not rare,False,A school is a ____,"school, college, building, community, structure",True,False,A school is not a ____,"school, church, university, home, place",False
10,11,daisy,flower,3.78,not rare,True,A daisy is a ____,"daisy, rose, flower, berry, tree",True,False,A daisy is not a ____,"daisy, rose, flower, lily, cherry",True
11,12,oak,tree,4.18,not rare,True,An oak is a ____,"tree, pine, forest, log, branch",True,True,An oak is not a ____,"tree, oak, pine, wood, forest",True
12,13,drill,tool,4.09,not rare,False,A drill is a ____,"drill, tool, machine, weapon, device",True,False,A drill is not a ____,"drill, tool, weapon, gun, bomb",True
13,14,daffodil,flower,2.56,rare (<3),False,A daffodil is a ____,"flower, butterfly, plant, vegetable, fruit",True,True,A daffodil is not a ____,"bird, flower, butterfly, tree, rose",True
14,15,cedar,tree,3.76,not rare,False,A cedar is a ____,"tree, cedar, pine, rock, stone",True,True,A cedar is not a ____,"cedar, tree, pine, stone, rock",True
15,16,salmon,fish,4.01,not rare,True,A salmon is a ____,"fish, salmon, trout, river, shark",True,True,A salmon is not a ____,"salmon, fish, trout, river, whale",True
16,17,hospital,building,5.07,not rare,False,A hospital is a ____,"hospital, building, place, clinic, prison",True,False,A hospital is not a ____,"hospital, prison, place, home, clinic",False
17,18,pine,tree,4.10,not rare,True,A pine is a ____,"tree, pine, forest, wood, nut",True,True,A pine is not a ____,"pine, tree, forest, nut, wood",True
18,19,ant,insect,3.86,not rare,True,An ant is an ____,"ant, insect, animal, organism, entity",True,False,An ant is not an ____,"ant, insect, animal, elephant, ape",True
19,20,radish,vegetable,2.78,rare (<3),False,A radish is a ____,"vegetable, fruit, dessert, variety, cereal",True,True,A radish is not a ____,"vegetable, tree, cake, fruit, bowl",True
20,21,van,vehicle,4.78,not rare,False,A van is a ____,"car, vehicle, truck, van, bus",True,False,A van is not a ____,"car, van, vehicle, truck, bus",True
21,22,lily,flower,3.95,not rare,False,A lily is a ____,"flower, lily, rose, plant, butterfly",True,True,A lily is not a ____,"rose, lily, flower, bird, butterfly",True
22,23,sparrow,bird,3.48,not rare,True,A sparrow is a ____,"bird, sparrow, crow, hawk, parrot",True,True,A sparrow is not a ____,"bird, sparrow, hawk, crow, chicken",True
23,24,grape,fruit,3.70,not rare,False,A grape is a ____,"grape, fruit, vine, wine, berry",True,False,A grape is not a ____,"grape, wine, vine, fruit, tree",True
24,25,bee,insect,4.09,not rare,True,A bee is an ____,"insect, animal, ant, organism, object",True,True,A bee is not an ____,"animal, insect, ant, object, angel",True
25,26,trowel,tool,2.45,rare (<3),False,A trowel is a ____,"tool, knife, weapon, shovel, blade",True,True,A trowel is not a ____,"tool, knife, weapon, blade, shovel",True
26,27,hammer,tool,4.16,not rare,True,A hammer is a ____,"hammer, tool, weapon, nail, device",True,False,A hammer is not a ____,"hammer, weapon, tool, gun, rock",True
27,28,hawk,bird,3.81,not rare,False,A hawk is a ____,"hawk, bird, hunter, predator, crow",True,False,A hawk is not a ____,"hawk, bird, falcon, fox, hunter",True
28,29,carrot,vegetable,3.62,not rare,True,A carrot is a ____,"carrot, vegetable, potato, stick, banana",True,False,A carrot is not a ____,"carrot, vegetable, potato, stick, banana",True
29,30,cauliflower,vegetable,3.20,not rare,False,A cauliflower is a ____,"vegetable, plant, flower, perennial, shrub",True,True,A cauliflower is not a ____,"vegetable, flower, plant, tree, fish",True
30,31,car,vehicle,5.45,not rare,True,A car is a ____,"car, vehicle, machine, truck, driver",True,False,A car is not a ____,"car, vehicle, truck, boat, machine",True
31,32,halibut,fish,2.71,rare (<3),False,A halibut is a ____,"fish, whale, shark, herring, dolphin",True,True,A halibut is not a ____,"fish, whale, salmon, shark, tuna",True
32,33,maple,tree,3.86,not rare,False,A maple is a ____,"tree, maple, plant, wood, shrub",True,True,A maple is not a ____,"maple, tree, leaf, pine, birch",True
33,34,larch,tree,2.55,rare (<3),False,A larch is a ____,"tree, shrub, fern, bush, plant",True,True,A larch is not a ____,"tree, shrub, bush, plant, fern",True
34,35,moped,vehicle,2.78,rare (<3),False,A moped is a ____,"bicycle, motorcycle, bike, vehicle, car",True,False,A moped is not a ____,"bicycle, car, bike, motorcycle, vehicle",True
35,36,rose,flower,4.82,not rare,True,A rose is a ____,"rose, flower, daisy, lily, woman",True,False,A rose is not a ____,"rose, flower, lily, daisy, stone",True
36,37,rickshaw,vehicle,2.85,rare (<3),False,A rickshaw is a ____,"taxi, vehicle, car, cart, carriage",True,False,A rickshaw is not a ____,"taxi, car, vehicle, bus, driver",True
37,38,lemon,fruit,4.10,not rare,False,A lemon is a ____,"lemon, lime, berry, fruit, rose",True,False,A lemon is not a ____,"lemon, lime, rose, plum, peach",False
38,39,cod,fish,3.89,not rare,False,A cod is a ____,"fish, lobster, crab, cod, boat",True,True,A cod is not a ____,"fish, cod, pig, boat, dog",True
39,40,onion,vegetable,3.89,not rare,False,An onion is a ____,"vegetable, plant, carrot, potato, mushroom",True,True,An onion is not a ____,"vegetable, potato, fish, carrot, human",True
40,41,truck,vehicle,4.64,not rare,True,A truck is a ____,"truck, car, vehicle, trailer, tractor",True,False,A truck is not a ____,"truck, car, vehicle, trailer, boat",True
41,42,eagle,bird,4.13,not rare,False,An eagle is a ____,"bird, falcon, crow, raven, hawk",True,True,An eagle is not a ____,"bird, raven, falcon, crow, hawk",True
42,43,willow,tree,3.69,not rare,False,A willow is a ____,"tree, willow, plant, shrub, leaf",True,True,A willow is not a ____,"willow, tree, reed, pine, witch",True
43,44,orchid,flower,3.30,not rare,False,An orchid is a ____,"plant, flower, tree, garden, weed",True,False,An orchid is not a ____,"plant, flower, tree, weed, bird",True
44,45,pagoda,building,2.85,rare (<3),False,A pagoda is a ____,"pagoda, building, structure, tower, pyramid",True,False,A pagoda is not a ____,"pagoda, temple, pyramid, tower, bridge",False
45,46,wrench,tool,3.37,not rare,False,A wrench is a ____,"tool, hammer, lever, weapon, device",True,True,A wrench is not a ____,"hammer, weapon, gun, knife, tool",True
46,47,robin,bird,4.33,not rare,True,A robin is a ____,"bird, robin, person, hunter, pigeon",True,True,A robin is not a ____,"robin, bird, penguin, man, fly",True
47,48,owl,bird,3.87,not rare,False,An owl is a ____,"bird, crow, raven, human, person",True,True,An owl is not a ____,"bird, human, dog, vampire, wolf",True
48,49,guava,fruit,2.61,rare (<3),False,A guava is a ____,"fruit, banana, plant, tree, vegetable",True,True,A guava is not a ____,"tree, banana, fruit, plant, vegetable",True
49,50,shark,fish,4.10,not rare,False,A shark is a ____,"shark, fish, monster, whale, predator",True,False,A shark is not a ____,"shark, fish, whale, dolphin, monster",True
50,51,bus,vehicle,4.83,not rare,False,A bus is a ____,"bus, car, vehicle, train, truck",True,False,A bus is not a ____,"bus, car, train, truck, vehicle",True
51,52,termite,insect,2.78,rare (<3),False,A termite is an ____,"insect, ant, organism, animal, infection",True,True,A termite is not an ____,"insect, ant, animal, organism, infection",True
52,53,shovel,tool,3.50,not rare,False,A shovel is a ____,"shovel, tool, hammer, weapon, spade",True,False,A shovel is not a ____,"shovel, tool, weapon, hammer, knife",True
53,54,turnip,vegetable,2.84,rare (<3),False,A turnip is a ____,"vegetable, carrot, potato, tree, plant",True,True,A turnip is not a ____,"vegetable, tree, fish, carrot, potato",True
54,55,sunflower,flower,3.36,not rare,False,A sunflower is a ____,"flower, plant, shrub, perennial, ##flower",True,True,A sunflower is not a ____,"flower, plant, seed, tree, rose",True
55,56,trout,fish,3.78,not rare,True,A trout is a ____,"fish, trout, salmon, species, predator",True,True,A trout is not a ____,"fish, trout, salmon, river, shark",True
56,57,haddock,fish,2.83,rare (<3),False,A haddock is a ____,"dog, fish, whale, pig, cow",True,False,A haddock is not a ____,"dog, fish, wolf, whale, pig",True
57,58,beetle,insect,3.53,not rare,False,A beetle is an ____,"insect, animal, organism, object, ant",True,True,A beetle is not an ____,"insect, animal, object, ant, organism",True
58,59,ladybug,insect,2.67,rare (<3),False,A ladybug is an ____,"insect, animal, owl, egg, elephant",True,True,A ladybug is not an ____,"animal, insect, object, angel, elephant",True
59,60,sycamore,tree,2.94,rare (<3),False,A sycamore is a ____,"tree, shrub, plant, bush, willow",True,True,A sycamore is not a ____,"tree, plant, weed, shrub, rose",True
60,61,potato,vegetable,4.11,not rare,False,A potato is a ____,"vegetable, potato, plant, cereal, food",True,True,A potato is not a ____,"potato, vegetable, plant, human, fish",True
61,62,house,building,5.71,not rare,True,A house is a ____,"house, building, dwelling, home, structure",True,False,A house is not a ____,"house, building, home, dwelling, place",True
62,63,wasp,insect,3.35,not rare,False,A wasp is an ____,"insect, animal, ant, organism, object",True,True,A wasp is not an ____,"insect, animal, ant, alien, egg",True
63,64,papaya,fruit,2.87,rare (<3),False,A papaya is a ____,"vegetable, banana, fruit, flower, plant",True,False,A papaya is not a ____,"banana, flower, vegetable, tree, rose",False
64,65,apple,fruit,4.76,not rare,False,An apple is a ____,"tree, fruit, pear, nut, vegetable",True,False,An apple is not a ____,"tree, apple, human, lemon, man",False
65,66,screwdriver,tool,3.13,not rare,False,A screwdriver is a ____,"tool, screw, hammer, knife, device",True,True,A screwdriver is not a ____,"tool, screw, knife, gun, weapon",True
66,67,woodpecker,bird,2.82,rare (<3),False,A woodpecker is a ____,"bird, crow, parrot, partridge, cuckoo",True,True,A woodpecker is not a ____,"bird, tree, species, hunter, squirrel",True
67,68,carnation,flower,2.70,rare (<3),False,A carnation is a ____,"flower, rose, plant, daisy, bouquet",True,True,A carnation is not a ____,"flower, rose, tree, diamond, daisy",True
68,69,peach,fruit,3.77,not rare,False,A peach is a ____,"peach, plum, berry, lemon, rose",False,False,A peach is not a ____,"peach, plum, berry, lemon, flower",False
69,70,tuna,fish,3.64,not rare,False,A tuna is a ____,"fish, tuna, shark, crab, dolphin",True,True,A tuna is not a ____,"fish, tuna, shark, whale, salmon",True

Table 13 — NEG-136-SIMP-BAL-RARE, BERT Base, all items (n=70)

,item,hyponym,category,zipf,frequency,Ettinger,Affirmative context,Top-5 (affirmative),category in top-5,category is top-1,Negated context,Top-5 (negated),category STILL in top-5 after 'not'
0,1,granary,building,2.57,rare (<3),False,A granary is a ____,"building, container, structure, refrigerator, compound",True,True,A granary is not a ____,"building, kitchen, structure, refrigerator, container",True
1,2,banana,fruit,4.00,not rare,False,A banana is a ____,"banana, fruit, plant, tree, vegetable",True,False,A banana is not a ____,"banana, fruit, tree, vegetable, bananas",True
2,3,hotel,building,4.95,not rare,True,A hotel is a ____,"hotel, business, resort, restaurant, building",True,False,A hotel is not a ____,"hotel, resort, motel, restaurant, business",False
3,4,moth,insect,3.50,not rare,False,A moth is an ____,"insect, animal, illusion, asteroid, ant",True,True,A moth is not an ____,"animal, insect, exception, organism, entity",True
4,5,chisel,tool,2.96,rare (<3),False,A chisel is a ____,"tool, weapon, hammer, blade, knife",True,True,A chisel is not a ____,"tool, hammer, weapon, knife, stone",True
5,6,train,vehicle,4.96,not rare,False,A train is a ____,"train, locomotive, car, thing, machine",False,False,A train is not a ____,"train, locomotive, car, vehicle, passenger",True
6,7,church,building,5.16,not rare,False,A church is a ____,"village, church, parish, cemetery, commune",False,False,A church is not a ____,"church, parish, community, sanctuary, religion",False
7,8,cabbage,vegetable,3.55,not rare,False,A cabbage is a ____,"cabbage, vegetable, plant, potato, soup",True,False,A cabbage is not a ____,"cabbage, vegetable, potato, tomato, bean",True
8,9,kestrel,bird,2.47,rare (<3),False,A kestrel is a ____,"horse, dog, bird, mammal, human",True,False,A kestrel is not a ____,"dog, bird, hunter, horse, cat",True
9,10,school,building,5.71,not rare,False,A school is a ____,"school, community, university, village, college",False,False,A school is not a ____,"school, community, college, university, village",False
10,11,daisy,flower,3.78,not rare,True,A daisy is a ____,"daisy, flower, plant, shrub, word",True,False,A daisy is not a ____,"daisy, flower, rose, tree, poem",True
11,12,oak,tree,4.18,not rare,True,An oak is a ____,"tree, forest, plant, shrub, species",True,True,An oak is not a ____,"tree, wood, forest, plant, shrub",True
12,13,drill,tool,4.09,not rare,False,A drill is a ____,"drill, tool, weapon, device, machine",True,False,A drill is not a ____,"drill, tool, weapon, problem, test",True
13,14,daffodil,flower,2.56,rare (<3),False,A daffodil is a ____,"plant, fruit, grape, chemical, flower",True,False,A daffodil is not a ____,"flower, plant, fruit, vegetable, poison",True
14,15,cedar,tree,3.76,not rare,False,A cedar is a ____,"tree, wood, shrub, timber, cedar",True,True,A cedar is not a ____,"tree, cedar, wood, timber, forest",True
15,16,salmon,fish,4.01,not rare,True,A salmon is a ____,"fish, salmon, trout, fishery, river",True,True,A salmon is not a ____,"salmon, fish, trout, species, snake",True
16,17,hospital,building,5.07,not rare,False,A hospital is a ____,"hospital, doctor, profession, building, business",True,False,A hospital is not a ____,"hospital, prison, doctor, building, facility",True
17,18,pine,tree,4.10,not rare,True,A pine is a ____,"tree, forest, wood, plant, shrub",True,True,A pine is not a ____,"tree, pine, forest, wood, plant",True
18,19,ant,insect,3.86,not rare,True,An ant is an ____,"ant, organism, insect, animal, ants",True,False,An ant is not an ____,"ant, animal, organism, insect, individual",True
19,20,radish,vegetable,2.78,rare (<3),False,A radish is a ____,"noun, plant, perfume, vegetable, compound",True,False,A radish is not a ____,"drug, commodity, noun, product, mineral",False
20,21,van,vehicle,4.78,not rare,False,A van is a ____,"van, vehicle, car, truck, transport",True,False,A van is not a ____,"van, vehicle, car, truck, trailer",True
21,22,lily,flower,3.95,not rare,False,A lily is a ____,"lily, flower, plant, symbol, rose",True,False,A lily is not a ____,"lily, flower, bird, rose, dove",True
22,23,sparrow,bird,3.48,not rare,True,A sparrow is a ____,"bird, sparrow, lark, pigeon, fly",True,True,A sparrow is not a ____,"bird, sparrow, lark, species, pigeon",True
23,24,grape,fruit,3.70,not rare,False,A grape is a ____,"grape, wine, vine, variety, fruit",True,False,A grape is not a ____,"grape, wine, variety, vineyard, fruit",True
24,25,bee,insect,4.09,not rare,True,A bee is an ____,"insect, animal, ant, organism, object",True,True,A bee is not an ____,"insect, animal, ant, organism, individual",True
25,26,trowel,tool,2.45,rare (<3),False,A trowel is a ____,"tool, weapon, blade, knife, device",True,True,A trowel is not a ____,"tool, weapon, blade, knife, device",True
26,27,hammer,tool,4.16,not rare,True,A hammer is a ____,"hammer, tool, weapon, device, firearm",True,False,A hammer is not a ____,"hammer, tool, weapon, gun, firearm",True
27,28,hawk,bird,3.81,not rare,False,A hawk is a ____,"bird, hawk, dog, falcon, snake",True,True,A hawk is not a ____,"hawk, bird, dog, predator, hunter",True
28,29,carrot,vegetable,3.62,not rare,True,A carrot is a ____,"carrot, plant, vegetable, weed, fruit",True,False,A carrot is not a ____,"carrot, plant, vegetable, potato, flower",True
29,30,cauliflower,vegetable,3.20,not rare,False,A cauliflower is a ____,"plant, flower, ##flower, shrub, perennial",False,False,A cauliflower is not a ____,"flower, plant, weed, tree, perennial",False
30,31,car,vehicle,5.45,not rare,True,A car is a ____,"car, vehicle, driver, concept, person",True,False,A car is not a ____,"car, vehicle, person, driver, automobile",True
31,32,halibut,fish,2.71,rare (<3),False,A halibut is a ____,"cocktail, salad, cake, pastry, dog",False,False,A halibut is not a ____,"meal, fish, meat, salad, food",True
32,33,maple,tree,3.86,not rare,False,A maple is a ____,"tree, plant, maple, variety, wood",True,True,A maple is not a ____,"tree, maple, wood, plant, species",True
33,34,larch,tree,2.55,rare (<3),False,A larch is a ____,"tree, noun, plant, bird, shrub",True,True,A larch is not a ____,"tree, bird, plant, fish, species",True
34,35,moped,vehicle,2.78,rare (<3),False,A moped is a ____,"bicycle, motorcycle, horse, dog, bike",False,False,A moped is not a ____,"bicycle, motorcycle, bike, horse, dog",False
35,36,rose,flower,4.82,not rare,True,A rose is a ____,"flower, rose, plant, poem, word",True,True,A rose is not a ____,"rose, flower, plant, thorn, daisy",True
36,37,rickshaw,vehicle,2.85,rare (<3),False,A rickshaw is a ____,"vehicle, transport, bicycle, car, driver",True,True,A rickshaw is not a ____,"vehicle, car, machine, transport, bicycle",True
37,38,lemon,fruit,4.10,not rare,False,A lemon is a ____,"lemon, fruit, drink, cocktail, grape",True,False,A lemon is not a ____,"lemon, fruit, lime, grape, tree",True
38,39,cod,fish,3.89,not rare,False,A cod is a ____,"cod, fish, crab, boat, vessel",True,False,A cod is not a ____,"cod, fish, ship, contract, band",True
39,40,onion,vegetable,3.89,not rare,False,An onion is a ____,"onion, plant, tomato, vegetable, dish",True,False,An onion is not a ____,"onion, vegetable, tomato, flower, plant",True
40,41,truck,vehicle,4.64,not rare,True,A truck is a ____,"truck, vehicle, car, driver, pickup",True,False,A truck is not a ____,"truck, vehicle, car, pickup, driver",True
41,42,eagle,bird,4.13,not rare,False,An eagle is a ____,"bird, symbol, seal, flag, falcon",True,True,An eagle is not a ____,"bird, symbol, threat, creature, species",True
42,43,willow,tree,3.69,not rare,False,A willow is a ____,"willow, tree, plant, flower, shrub",True,False,A willow is not a ____,"willow, tree, plant, flower, shrub",True
43,44,orchid,flower,3.30,not rare,False,An orchid is a ____,"plant, orchid, flower, weed, shrub",True,False,An orchid is not a ____,"plant, flower, orchid, weed, species",True
44,45,pagoda,building,2.85,rare (<3),False,A pagoda is a ____,"pagoda, building, temple, symbol, structure",True,False,A pagoda is not a ____,"pagoda, temple, church, building, monastery",True
45,46,wrench,tool,3.37,not rare,False,A wrench is a ____,"tool, weapon, firearm, device, gun",True,True,A wrench is not a ____,"tool, weapon, machine, device, hammer",True
46,47,robin,bird,4.33,not rare,True,A robin is a ____,"robin, bird, pigeon, flower, dog",True,False,A robin is not a ____,"robin, bird, pigeon, dog, lion",True
47,48,owl,bird,3.87,not rare,False,An owl is a ____,"bird, mammal, owl, raven, pigeon",True,True,An owl is not a ____,"bird, owl, mammal, dog, raven",True
48,49,guava,fruit,2.61,rare (<3),False,A guava is a ____,"grape, fruit, beer, drink, wine",True,False,A guava is not a ____,"wine, drink, fruit, grape, beer",True
49,50,shark,fish,4.10,not rare,False,A shark is a ____,"shark, fish, predator, snake, concept",True,False,A shark is not a ____,"shark, fish, predator, monster, creature",True
50,51,bus,vehicle,4.83,not rare,False,A bus is a ____,"bus, vehicle, car, driver, transport",True,False,A bus is not a ____,"bus, vehicle, car, coach, transport",True
51,52,termite,insect,2.78,rare (<3),False,A termite is an ____,"asteroid, explosive, object, element, aggregate",False,False,A termite is not an ____,"object, asteroid, explosive, element, animal",False
52,53,shovel,tool,3.50,not rare,False,A shovel is a ____,"shovel, tool, weapon, spade, knife",True,False,A shovel is not a ____,"shovel, tool, weapon, knife, spade",True
53,54,turnip,vegetable,2.84,rare (<3),False,A turnip is a ____,"carrot, dog, vegetable, potato, fruit",True,False,A turnip is not a ____,"dog, vegetable, potato, carrot, cat",True
54,55,sunflower,flower,3.36,not rare,False,A sunflower is a ____,"flower, plant, ##flower, tree, shrub",True,True,A sunflower is not a ____,"flower, plant, tree, ##flower, vegetable",True
55,56,trout,fish,3.78,not rare,True,A trout is a ____,"fish, trout, fishery, stream, species",True,True,A trout is not a ____,"trout, fish, species, salmon, fishery",True
56,57,haddock,fish,2.83,rare (<3),False,A haddock is a ____,"horse, dog, noun, ship, name",False,False,A haddock is not a ____,"horse, dog, man, person, cow",False
57,58,beetle,insect,3.53,not rare,False,A beetle is an ____,"animal, example, insect, exception, object",True,False,A beetle is not an ____,"exception, animal, insect, entity, option",True
58,59,ladybug,insect,2.67,rare (<3),False,A ladybug is an ____,"animal, insect, apple, adjective, object",True,False,A ladybug is not an ____,"animal, insect, exception, ant, adult",True
59,60,sycamore,tree,2.94,rare (<3),False,A sycamore is a ____,"plant, tree, flower, shrub, fruit",True,False,A sycamore is not a ____,"tree, plant, flower, weed, fruit",True
60,61,potato,vegetable,4.11,not rare,False,A potato is a ____,"potato, vegetable, plant, cake, dessert",True,False,A potato is not a ____,"potato, vegetable, food, plant, meal",True
61,62,house,building,5.71,not rare,True,A house is a ____,"house, building, property, family, place",True,False,A house is not a ____,"house, home, dwelling, household, building",True
62,63,wasp,insect,3.35,not rare,False,A wasp is an ____,"insect, ant, animal, exception, organism",True,True,A wasp is not an ____,"insect, animal, exception, ant, organism",True
63,64,papaya,fruit,2.87,rare (<3),False,A papaya is a ____,"tree, plant, shrub, flower, fruit",True,False,A papaya is not a ____,"tree, plant, flower, shrub, vegetable",False
64,65,apple,fruit,4.76,not rare,False,An apple is a ____,"fruit, tree, apple, plant, flower",True,True,An apple is not a ____,"tree, fruit, apple, bird, flower",True
65,66,screwdriver,tool,3.13,not rare,False,A screwdriver is a ____,"tool, screw, knife, device, firearm",True,True,A screwdriver is not a ____,"tool, firearm, screw, weapon, device",True
66,67,woodpecker,bird,2.82,rare (<3),False,A woodpecker is a ____,"bird, mammal, pigeon, parrot, deer",True,True,A woodpecker is not a ____,"bird, predator, mammal, species, dog",True
67,68,carnation,flower,2.70,rare (<3),False,A carnation is a ____,"flower, plant, fruit, name, symbol",True,True,A carnation is not a ____,"flower, name, surname, car, symbol",True
68,69,peach,fruit,3.77,not rare,False,A peach is a ____,"peach, fruit, flower, dessert, tree",True,False,A peach is not a ____,"peach, cherry, fruit, flower, tree",True
69,70,tuna,fish,3.64,not rare,False,A tuna is a ____,"tuna, fish, container, vessel, snack",True,False,A tuna is not a ____,"tuna, fish, shark, food, whale",True

BERT Large — overall

            n  aff_top5  aff_top1  still_top5_after_not
all items  70        68        39                    61

BERT Large — rare vs not rare

            n  aff_top5  aff_top1  still_top5_after_not
frequency
not rare   50        48        24                    43
rare (<3)  20        20        15                    18

BERT Large — per category

           n  aff_top5  aff_top1  still_top5_after_not
category
bird       7         7         6                     7
building   7         6         1                     3
fish       7         7         5                     7
flower     7         7         4                     7
fruit      7         6         1                     3
insect     7         7         6                     7
tool       7         7         4                     7
tree       7         7         7                     7
vegetable  7         7         5                     7
vehicle    7         7         0                     6

BERT Base — overall

            n  aff_top5  aff_top1  still_top5_after_not
all items  70        62        25                    61

BERT Base — rare vs not rare

            n  aff_top5  aff_top1  still_top5_after_not
frequency
not rare   50        46        18                    46
rare (<3)  20        16         7                    15

BERT Base — per category

           n  aff_top5  aff_top1  still_top5_after_not
category
bird       7         7         5                     7
building   7         5         1                     4
fish       7         5         2                     6
flower     7         7         3                     7
fruit      7         7         1                     6
insect     7         6         3                     6
tool       7         7         4                     7
tree       7         7         5                     7
vegetable  7         6         0                     5
vehicle    7         5         1                     6

Items where the category is NOT in the affirmative top-5:

,Model,item,hyponym,category,zipf,frequency,Top-5 (affirmative)
5,BERT Base,6,train,vehicle,4.96,not rare,"train, locomotive, car, thing, machine"
6,BERT Base,7,church,building,5.16,not rare,"village, church, parish, cemetery, commune"
9,BERT Base,10,school,building,5.71,not rare,"school, community, university, village, college"
29,BERT Base,30,cauliflower,vegetable,3.20,not rare,"plant, flower, ##flower, shrub, perennial"
31,BERT Base,32,halibut,fish,2.71,rare (<3),"cocktail, salad, cake, pastry, dog"
34,BERT Base,35,moped,vehicle,2.78,rare (<3),"bicycle, motorcycle, horse, dog, bike"
51,BERT Base,52,termite,insect,2.78,rare (<3),"asteroid, explosive, object, element, aggregate"
56,BERT Base,57,haddock,fish,2.83,rare (<3),"horse, dog, noun, ship, name"
76,BERT Large,7,church,building,5.16,not rare,"church, cathedral, parish, monastery, temple"
138,BERT Large,69,peach,fruit,3.77,not rare,"peach, plum, berry, lemon, rose"

In [ ]:

print("SIMP-BAL — BERT Base")
display(audit(bal_base))

print("SIMP-BAL — BERT Large")
display(audit(bal_large))

SIMP-BAL — BERT Base

cond,item,FA,FN,TA,TN,TA>FA,TN>FN,TA-FA,TN-FN
0,1,2.020712e-05,0.133582,0.155367,6.996226e-06,True,False,0.155347,-0.133575
1,10,3.585854e-04,0.001903,0.013419,7.779888e-05,True,False,0.013061,-0.001825
2,11,1.967524e-04,0.072219,0.054946,6.657573e-04,True,False,0.054749,-0.071553
3,12,4.208911e-05,0.927698,0.797508,4.915193e-05,True,False,0.797466,-0.927649
4,13,7.137485e-05,0.005584,0.057710,8.337881e-06,True,False,0.057639,-0.005575
5,14,1.713753e-04,0.063732,0.032233,4.419597e-04,True,False,0.032061,-0.063290
6,15,3.233316e-04,0.698534,0.836194,1.739339e-04,True,False,0.835871,-0.698360
7,16,2.939885e-04,0.372949,0.468620,7.392465e-05,True,False,0.468326,-0.372875
8,17,1.316093e-04,0.001202,0.014942,1.407258e-06,True,False,0.014810,-0.001200
9,18,9.493683e-05,0.542941,0.770262,2.896631e-04,True,False,0.770167,-0.542652
10,19,3.694899e-04,0.009920,0.023876,6.548225e-04,True,False,0.023507,-0.009265
11,2,1.135275e-03,0.030599,0.029849,1.134910e-03,True,False,0.028714,-0.029464
12,20,1.368072e-02,0.020807,0.019873,3.095311e-03,True,False,0.006192,-0.017712
13,21,3.972108e-05,0.152167,0.287324,6.108770e-05,True,False,0.287284,-0.152106
14,22,1.539557e-04,0.062547,0.287754,1.137896e-04,True,False,0.287600,-0.062433
15,23,2.149893e-05,0.535142,0.545084,1.468437e-05,True,False,0.545063,-0.535127
16,24,3.444896e-03,0.008690,0.019361,3.172469e-03,True,False,0.015916,-0.005517
17,25,7.375481e-04,0.612482,0.726103,8.571031e-05,True,False,0.725365,-0.612396
18,26,7.007181e-05,0.512814,0.360969,4.081568e-05,True,False,0.360899,-0.512773
19,27,5.776042e-04,0.177014,0.325408,4.986854e-04,True,False,0.324830,-0.176515
20,28,7.902379e-06,0.251473,0.507206,3.552219e-06,True,False,0.507199,-0.251469
21,29,4.441910e-05,0.007566,0.001668,6.144525e-04,True,False,0.001624,-0.006952
22,3,4.752328e-06,0.002389,0.018337,3.913319e-07,True,False,0.018333,-0.002389
23,30,2.557407e-04,0.018282,0.014723,2.288324e-04,True,False,0.014467,-0.018053
24,31,9.490212e-05,0.238066,0.243470,1.194748e-04,True,False,0.243375,-0.237947
25,32,9.279175e-04,0.082277,0.023150,2.956165e-04,True,False,0.022222,-0.081981
26,33,7.215938e-04,0.593156,0.622384,5.170745e-03,True,False,0.621662,-0.587985
27,34,2.613226e-03,0.124011,0.138088,2.509078e-02,True,False,0.135475,-0.098920
28,35,2.371734e-05,0.052446,0.026694,5.185651e-05,True,False,0.026670,-0.052394
29,36,2.200209e-03,0.303401,0.511275,1.144714e-03,True,False,0.509075,-0.302256
30,37,5.809820e-06,0.404547,0.296183,7.461539e-06,True,False,0.296177,-0.404540
31,38,3.119863e-04,0.007984,0.016484,4.197220e-04,True,False,0.016172,-0.007565
32,39,5.012562e-04,0.014173,0.080871,1.863600e-04,True,False,0.080369,-0.013987
33,4,1.723101e-02,0.115405,0.168546,5.156281e-02,True,False,0.151315,-0.063842
34,40,1.316642e-04,0.096830,0.047267,3.069415e-04,True,False,0.047135,-0.096523
35,41,1.624173e-05,0.103839,0.239107,4.882722e-06,True,False,0.239090,-0.103835
36,42,1.557055e-05,0.759973,0.608354,1.005994e-05,True,False,0.608339,-0.759963
37,43,6.438034e-05,0.270179,0.244778,2.620932e-05,True,False,0.244713,-0.270152
38,44,4.090154e-04,0.147051,0.089978,5.635579e-04,True,False,0.089569,-0.146487
39,45,4.299677e-04,0.013603,0.053299,2.323052e-04,True,False,0.052869,-0.013370
40,46,1.494913e-04,0.410881,0.323330,2.226472e-04,True,False,0.323180,-0.410659
41,47,5.804135e-03,0.096690,0.315533,2.640250e-03,True,False,0.309729,-0.094050
42,48,4.184943e-04,0.797256,0.841009,4.285723e-05,True,False,0.840591,-0.797213
43,49,1.459521e-03,0.047566,0.096402,3.327738e-03,True,False,0.094942,-0.044238
44,5,3.886717e-05,0.623186,0.619467,2.959350e-05,True,False,0.619428,-0.623156
45,50,2.209339e-04,0.161986,0.109167,1.443443e-04,True,False,0.108946,-0.161842
46,51,3.818682e-05,0.038466,0.055385,5.764156e-06,True,False,0.055347,-0.038460
47,52,1.053903e-03,0.002725,0.003596,2.704541e-03,True,False,0.002543,-0.000020
48,53,4.679143e-07,0.136384,0.271891,1.015610e-06,True,False,0.271891,-0.136383
49,54,4.397991e-04,0.074541,0.030062,4.129184e-04,True,False,0.029622,-0.074128
50,55,1.949818e-02,0.626897,0.691479,1.037625e-02,True,False,0.671981,-0.616521
51,56,4.542578e-04,0.282158,0.458702,7.007256e-05,True,False,0.458248,-0.282088
52,57,7.158147e-04,0.004245,0.005043,1.040871e-03,True,False,0.004327,-0.003204
53,58,1.391719e-04,0.056767,0.045481,3.090873e-04,True,False,0.045342,-0.056458
54,59,4.472582e-03,0.044957,0.126981,2.695434e-03,True,False,0.122508,-0.042262
55,6,3.058403e-05,0.017833,0.011670,1.739755e-05,True,False,0.011639,-0.017816
56,60,1.579076e-04,0.253541,0.260540,1.990760e-04,True,False,0.260382,-0.253341
57,61,2.186161e-03,0.057409,0.042298,2.063873e-03,True,False,0.040112,-0.055345
58,62,1.199932e-04,0.013464,0.055227,1.260634e-05,True,False,0.055107,-0.013451
59,63,6.627414e-04,0.420898,0.609445,8.262045e-04,True,False,0.608782,-0.420072
60,64,2.570869e-02,0.031711,0.041768,4.868496e-02,True,True,0.016059,0.016974
61,65,5.414155e-04,0.119243,0.294496,7.752595e-04,True,False,0.293954,-0.118468
62,66,4.483982e-06,0.462445,0.541685,6.302415e-06,True,False,0.541681,-0.462439
63,67,7.814641e-05,0.687315,0.895282,5.194820e-04,True,False,0.895204,-0.686795
64,68,3.670729e-02,0.080532,0.315480,1.067516e-02,True,False,0.278772,-0.069857
65,69,5.899711e-05,0.007211,0.083704,1.857421e-05,True,False,0.083645,-0.007193
66,7,6.986086e-06,0.014028,0.004867,3.052241e-05,True,False,0.004860,-0.013998
67,70,1.624417e-05,0.243371,0.186150,6.481146e-06,True,False,0.186134,-0.243364
68,8,3.339333e-06,0.035227,0.069760,1.085977e-05,True,False,0.069757,-0.035216
69,9,9.379172e-03,0.051112,0.071222,3.516094e-03,True,False,0.061843,-0.047595

SIMP-BAL — BERT Large

cond,item,FA,FN,TA,TN,TA>FA,TN>FN,TA-FA,TN-FN
0,1,2.075413e-05,0.051361,0.247394,0.000010,True,False,0.247373,-0.051351
1,10,3.383576e-05,0.010343,0.028303,0.000189,True,False,0.028269,-0.010153
2,11,1.615921e-03,0.011399,0.086995,0.000451,True,False,0.085379,-0.010948
3,12,1.830772e-04,0.774649,0.744313,0.000085,True,False,0.744129,-0.774564
4,13,1.557600e-04,0.013861,0.169594,0.000260,True,False,0.169438,-0.013601
5,14,1.991293e-05,0.099095,0.431361,0.000078,True,False,0.431341,-0.099017
6,15,8.261104e-04,0.090728,0.495718,0.000145,True,False,0.494892,-0.090583
7,16,3.734195e-05,0.350676,0.597984,0.000058,True,False,0.597947,-0.350618
8,17,4.836871e-05,0.005710,0.023273,0.000079,True,False,0.023224,-0.005631
9,18,4.276712e-04,0.209651,0.522395,0.000156,True,False,0.521968,-0.209495
10,19,4.741871e-03,0.085352,0.321126,0.002807,True,False,0.316385,-0.082545
11,2,9.315600e-03,0.008659,0.056814,0.003568,True,False,0.047498,-0.005091
12,20,1.386625e-02,0.068871,0.242960,0.005166,True,False,0.229094,-0.063705
13,21,8.594950e-05,0.075974,0.241186,0.000045,True,False,0.241100,-0.075930
14,22,1.505970e-04,0.155954,0.385877,0.000046,True,False,0.385727,-0.155908
15,23,6.238372e-06,0.462497,0.580487,0.000002,True,False,0.580480,-0.462495
16,24,1.198740e-02,0.038549,0.173541,0.022095,True,False,0.161553,-0.016454
17,25,1.984505e-04,0.358430,0.491372,0.000052,True,False,0.491174,-0.358378
18,26,1.631913e-04,0.254130,0.548411,0.000297,True,False,0.548248,-0.253833
19,27,1.688860e-03,0.095098,0.151806,0.002493,True,False,0.150117,-0.092605
20,28,9.941931e-06,0.117720,0.199188,0.000004,True,False,0.199178,-0.117716
21,29,4.686711e-03,0.015102,0.040064,0.003551,True,False,0.035377,-0.011551
22,3,4.108865e-06,0.008605,0.031087,0.000008,True,False,0.031083,-0.008597
23,30,2.112795e-06,0.171025,0.273992,0.000014,True,False,0.273990,-0.171011
24,31,1.478665e-04,0.066921,0.167242,0.000285,True,False,0.167094,-0.066637
25,32,1.792996e-07,0.598545,0.747163,0.000003,True,False,0.747163,-0.598541
26,33,5.886293e-03,0.153351,0.700857,0.002860,True,False,0.694971,-0.150491
27,34,1.900037e-06,0.816876,0.729003,0.000034,True,False,0.729001,-0.816842
28,35,2.505168e-07,0.063181,0.025282,0.000025,True,False,0.025281,-0.063155
29,36,2.698447e-03,0.058658,0.080181,0.001701,True,False,0.077483,-0.056958
30,37,1.405549e-05,0.063263,0.132488,0.000041,True,False,0.132474,-0.063222
31,38,7.774672e-04,0.001003,0.007225,0.000307,True,False,0.006447,-0.000696
32,39,2.429070e-05,0.286416,0.705835,0.000145,True,False,0.705810,-0.286271
33,4,5.333875e-02,0.311898,0.346798,0.111222,True,False,0.293459,-0.200676
34,40,4.901357e-04,0.125929,0.377483,0.000688,True,False,0.376992,-0.125241
35,41,2.992286e-06,0.036160,0.029305,0.000007,True,False,0.029302,-0.036153
36,42,2.534262e-05,0.390620,0.421886,0.000041,True,False,0.421861,-0.390580
37,43,4.807106e-04,0.219902,0.602483,0.000050,True,False,0.602002,-0.219852
38,44,2.001265e-04,0.222404,0.109919,0.003773,True,False,0.109719,-0.218632
39,45,1.509665e-04,0.033831,0.226314,0.000477,True,False,0.226163,-0.033354
40,46,5.821977e-06,0.061282,0.226716,0.000028,True,False,0.226710,-0.061254
41,47,9.511339e-03,0.087829,0.247797,0.002373,True,False,0.238286,-0.085456
42,48,7.329990e-05,0.353895,0.345756,0.000062,True,False,0.345683,-0.353833
43,49,1.907199e-03,0.063920,0.312175,0.014174,True,False,0.310268,-0.049747
44,5,1.215696e-05,0.385658,0.652295,0.000109,True,False,0.652283,-0.385549
45,50,2.767299e-05,0.086271,0.049733,0.000017,True,False,0.049705,-0.086253
46,51,2.578879e-05,0.017085,0.102487,0.000038,True,False,0.102461,-0.017047
47,52,4.981051e-04,0.323087,0.521572,0.002005,True,False,0.521074,-0.321081
48,53,1.837993e-05,0.053064,0.326184,0.000006,True,False,0.326166,-0.053058
49,54,5.458232e-06,0.166147,0.545516,0.000028,True,False,0.545510,-0.166119
50,55,1.531387e-01,0.593272,0.571005,0.149622,True,False,0.417866,-0.443649
51,56,5.491714e-05,0.539623,0.825476,0.000059,True,False,0.825421,-0.539563
52,57,2.760177e-06,0.099282,0.124753,0.000018,True,False,0.124750,-0.099264
53,58,1.836060e-03,0.473546,0.732155,0.001098,True,False,0.730319,-0.472448
54,59,3.027936e-03,0.076305,0.391866,0.000902,True,False,0.388838,-0.075403
55,6,1.105236e-05,0.017524,0.087568,0.000017,True,False,0.087557,-0.017506
56,60,1.189320e-04,0.836217,0.718003,0.000081,True,False,0.717884,-0.836136
57,61,1.787818e-02,0.105636,0.172383,0.001890,True,False,0.154505,-0.103746
58,62,2.588838e-06,0.080459,0.217257,0.000033,True,False,0.217254,-0.080427
59,63,3.784453e-03,0.685378,0.747336,0.003799,True,False,0.743551,-0.681579
60,64,1.665600e-01,0.018339,0.076634,0.046676,False,True,-0.089926,0.028336
61,65,8.826244e-04,0.013270,0.047198,0.000187,True,False,0.046316,-0.013083
62,66,6.542071e-07,0.271068,0.619763,0.000022,True,False,0.619762,-0.271045
63,67,2.798172e-06,0.608902,0.814732,0.000022,True,False,0.814729,-0.608880
64,68,2.809986e-03,0.468953,0.914537,0.001356,True,False,0.911727,-0.467597
65,69,2.601738e-05,0.000734,0.002530,0.000014,True,False,0.002504,-0.000720
66,7,1.250606e-05,0.036815,0.032786,0.000072,True,False,0.032773,-0.036744
67,70,3.717577e-06,0.320757,0.630327,0.000019,True,False,0.630323,-0.320739
68,8,1.494673e-05,0.023530,0.182008,0.000001,True,False,0.181993,-0.023529
69,9,1.136225e-05,0.431292,0.711930,0.000100,True,False,0.711919,-0.431193

In [ ]:

cmp11 = pd.concat([table11.assign(Dataset="NEG-136-SIMP"),
                   table11_bal.assign(Dataset="NEG-136-SIMP-BAL")])
cmp11 = cmp11[["Dataset", "Model", "k1_pct", "k1_correct", "k1_n", "k5_pct", "k5_correct", "k5_n"]]
print("Table 11 comparison")
display(cmp11.reset_index(drop=True))

cmp12 = pd.concat([table12.assign(Dataset="NEG-136-SIMP", Threshold="none"),
                   table12_threshold.assign(Dataset="NEG-136-SIMP", Threshold="0.01"),
                   table12_bal.assign(Dataset="NEG-136-SIMP-BAL", Threshold="none"),
                   table12_bal_threshold.assign(Dataset="NEG-136-SIMP-BAL", Threshold="0.01")])
cmp12 = cmp12[["Dataset", "Threshold", "Model", "Affirmative", "Negative", "Aff_correct", "Neg_correct", "n"]]
print("Table 12 comparison")
display(cmp12.reset_index(drop=True))

Table 11 comparison

,Dataset,Model,k1_pct,k1_correct,k1_n,k5_pct,k5_correct,k5_n
0,NEG-136-SIMP,BERT Base,38.888889,7,18,100.000000,18,18
1,NEG-136-SIMP,BERT Large,44.444444,8,18,100.000000,18,18
2,NEG-136-SIMP-BAL,BERT Base,35.714286,25,70,88.571429,62,70
3,NEG-136-SIMP-BAL,BERT Large,55.714286,39,70,97.142857,68,70

Table 12 comparison

,Dataset,Threshold,Model,Affirmative,Negative,Aff_correct,Neg_correct,n
0,NEG-136-SIMP,none,BERT Base,100.000000,0.000000,18,0,18
1,NEG-136-SIMP,none,BERT Large,100.000000,0.000000,18,0,18
2,NEG-136-SIMP,0.01,BERT Base,94.444444,0.000000,17,0,18
3,NEG-136-SIMP,0.01,BERT Large,100.000000,0.000000,18,0,18
4,NEG-136-SIMP-BAL,none,BERT Base,100.000000,1.428571,70,1,70
5,NEG-136-SIMP-BAL,none,BERT Large,98.571429,1.428571,69,1,70
6,NEG-136-SIMP-BAL,0.01,BERT Base,92.857143,1.428571,65,1,70
7,NEG-136-SIMP-BAL,0.01,BERT Large,95.714286,1.428571,67,1,70

In [ ]:
# ---- Optional extra (not in the paper): results per category, which the balanced design makes comparable ----
def per_category(scored, raw, model_name):
    w = wide_probs(scored)
    w["category"] = w["item"].map(dict(zip(raw["item"].astype(str), raw["target_aff"])))
    ta = scored[scored.cond == "TA"].copy()
    ta["k1"] = [row.expected in row.top_tokens[:1] for _, row in ta.iterrows()]
    ta["k5"] = [row.expected in row.top_tokens[:5] for _, row in ta.iterrows()]
    w = w.merge(ta[["item", "k1", "k5"]], on="item")
    g = w.groupby("category")[["TA", "FA", "TN", "FN", "k1", "k5"]].apply(lambda d: pd.Series({
        "n": len(d),
        "k1_pct": 100 * d.k1.mean(),
        "k5_pct": 100 * d.k5.mean(),
        "Affirmative": 100 * (d.TA > d.FA).mean(),
        "Negative": 100 * (d.TN > d.FN).mean(),
    }))
    return g.reset_index().assign(Model=model_name)

per_cat_bal = pd.concat([per_category(bal_base, bal_raw, "BERT Base"),
                         per_category(bal_large, bal_raw, "BERT Large")])
display(per_cat_bal[["Model", "category", "n", "k1_pct", "k5_pct", "Affirmative", "Negative"]].reset_index(drop=True))

         Model   category    n      k1_pct      k5_pct  Affirmative   Negative
0    BERT Base       bird  7.0   71.428571  100.000000   100.000000   0.000000
1    BERT Base   building  7.0   14.285714   71.428571   100.000000   0.000000
2    BERT Base       fish  7.0   28.571429   71.428571   100.000000   0.000000
3    BERT Base     flower  7.0   42.857143  100.000000   100.000000   0.000000
4    BERT Base      fruit  7.0   14.285714  100.000000   100.000000  14.285714
5    BERT Base     insect  7.0   42.857143   85.714286   100.000000   0.000000
6    BERT Base       tool  7.0   57.142857  100.000000   100.000000   0.000000
7    BERT Base       tree  7.0   71.428571  100.000000   100.000000   0.000000
8    BERT Base  vegetable  7.0    0.000000   85.714286   100.000000   0.000000
9    BERT Base    vehicle  7.0   14.285714   71.428571   100.000000   0.000000
10  BERT Large       bird  7.0   85.714286  100.000000   100.000000   0.000000
11  BERT Large   building  7.0   14.285714   85.714286   100.000000   0.000000
12  BERT Large       fish  7.0   71.428571  100.000000   100.000000   0.000000
13  BERT Large     flower  7.0   57.142857  100.000000   100.000000   0.000000
14  BERT Large      fruit  7.0   14.285714   85.714286    85.714286  14.285714
15  BERT Large     insect  7.0   85.714286  100.000000   100.000000   0.000000
16  BERT Large       tool  7.0   57.142857  100.000000   100.000000   0.000000
17  BERT Large       tree  7.0  100.000000  100.000000   100.000000   0.000000
18  BERT Large  vegetable  7.0   71.428571  100.000000   100.000000   0.000000
19  BERT Large    vehicle  7.0    0.000000  100.000000   100.000000   0.000000