In [ ]:
!pip -q install transformers pandas
!git clone -q https://github.com/aetting/lm-diagnostics.git

fatal: destination path 'lm-diagnostics' already exists and is not an empty directory.

In [ ]:
import os, re, torch, numpy as np, pandas as pd
from transformers import BertTokenizer, BertForMaskedLM

REPO = "/content/lm-diagnostics"
SIMP_PATH = f"{REPO}/datasets/NEG-136/NEG-136-SIMP.tsv"
NAT_PATH  = f"{REPO}/datasets/NEG-136/NEG-136-NAT.tsv"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)

simp_raw = pd.read_csv(SIMP_PATH, sep="\t")
nat_raw  = pd.read_csv(NAT_PATH, sep="\t")

print("SIMP:", simp_raw.shape)
print("NAT :", nat_raw.shape)
display(simp_raw.head())
display(nat_raw.head())

device: cuda
SIMP: (18, 5)
NAT : (16, 6)

   item         context_aff             context_neg target_aff target_neg
0     0   A trout is (a|an)   A trout is not (a|an)       fish       tool
1     1  A salmon is (a|an)  A salmon is not (a|an)       fish     flower
2     2    An ant is (a|an)    An ant is not (a|an)     insect  vegetable
3     3     A bee is (a|an)     A bee is not (a|an)     insect   building
4     4   A robin is (a|an)   A robin is not (a|an)       bird       tree

,item,context_aff,context_neg,target_aff,target_neg,licensing
0,0,"With proper equipment, scuba-diving is very","With proper equipment, scuba-diving isn't very",safe,dangerous,Y
1,1,Traveling in Baghdad is very,Traveling in Baghdad isn't very,dangerous,safe,Y
2,2,"In moderation, drinking red wine is","In moderation, drinking red wine isn't",good,bad,Y
3,3,Drinking tap water in developing countries is ...,Drinking tap water in developing countries isn...,dangerous,safe,Y
4,4,Secondhand furniture is very,Secondhand furniture isn't very,cheap,expensive,Y

In [ ]:
def process_negsimp(path):
    rows = []
    df = pd.read_csv(path, sep="\t")

    for _, r in df.iterrows():
        affsent = re.sub(r" \(.+\)", "", r["context_aff"])
        negsent = re.sub(r" \(.+\)", "", r["context_neg"])
        afftgt = r["target_aff"].strip()
        negtgt = r["target_neg"].strip()

        for sent, tgt, cond in [
            (affsent, afftgt, "TA"),
            (negsent, afftgt, "FN"),
            (affsent, negtgt, "FA"),
            (negsent, negtgt, "TN"),
        ]:
            det = "an" if re.match(r"[aeiou]", tgt) else "a"
            context = f"{sent} {det} [MASK]"
            expected = afftgt if cond in ("TA", "FA") else negtgt
            rows.append({
                "item": str(r["item"]),
                "cond": cond,
                "context": context,
                "target": tgt,
                "expected": expected,
            })
    return pd.DataFrame(rows)


def process_negnat(path):
    rows = []
    df = pd.read_csv(path, sep="\t")

    for _, r in df.iterrows():
        affsent = r["context_aff"].strip()
        negsent = r["context_neg"].strip()
        afftgt = r["target_aff"].strip()
        negtgt = r["target_neg"].strip()

        for sent, tgt, cond in [
            (affsent, afftgt, "TA"),
            (negsent, afftgt, "FN"),
            (affsent, negtgt, "FA"),
            (negsent, negtgt, "TN"),
        ]:
            context = f"{sent} [MASK]"
            expected = afftgt if cond in ("TA", "FA") else negtgt
            rows.append({
                "item": str(r["item"]),
                "cond": cond,
                "context": context,
                "target": tgt,
                "expected": expected,
                "licensing": r["licensing"],
            })
    return pd.DataFrame(rows)

simp = process_negsimp(SIMP_PATH)
nat = process_negnat(NAT_PATH)

assert len(simp) == 18 * 4
assert len(nat) == 16 * 4
assert set(simp.cond) == {"TA","FN","FA","TN"}
assert set(nat.cond) == {"TA","FN","FA","TN"}

display(simp.head(8))
display(nat.head(8))

  item cond                   context  target expected
0    0   TA       A trout is a [MASK]    fish     fish
1    0   FN   A trout is not a [MASK]    fish     tool
2    0   FA       A trout is a [MASK]    tool     fish
3    0   TN   A trout is not a [MASK]    tool     tool
4    1   TA      A salmon is a [MASK]    fish     fish
5    1   FN  A salmon is not a [MASK]    fish   flower
6    1   FA      A salmon is a [MASK]  flower     fish
7    1   TN  A salmon is not a [MASK]  flower   flower

,item,cond,context,target,expected,licensing
0,0,TA,"With proper equipment, scuba-diving is very [M...",safe,safe,Y
1,0,FN,"With proper equipment, scuba-diving isn't very...",safe,dangerous,Y
2,0,FA,"With proper equipment, scuba-diving is very [M...",dangerous,safe,Y
3,0,TN,"With proper equipment, scuba-diving isn't very...",dangerous,dangerous,Y
4,1,TA,Traveling in Baghdad is very [MASK],dangerous,dangerous,Y
5,1,FN,Traveling in Baghdad isn't very [MASK],dangerous,safe,Y
6,1,FA,Traveling in Baghdad is very [MASK],safe,dangerous,Y
7,1,TN,Traveling in Baghdad isn't very [MASK],safe,safe,Y

In [ ]:
def load_bert(name):
    tok = BertTokenizer.from_pretrained(name)
    model = BertForMaskedLM.from_pretrained(name).to(device)
    model.eval()
    return tok, model

tok_base, bert_base = load_bert("bert-base-uncased")
tok_large, bert_large = load_bert("bert-large-uncased")
print("Models loaded.")

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

[transformers] BertForMaskedLM LOAD REPORT from: bert-base-uncased
Key                         | Status     |  |
----------------------------+------------+--+-
bert.pooler.dense.bias      | UNEXPECTED |  |
cls.seq_relationship.weight | UNEXPECTED |  |
bert.pooler.dense.weight    | UNEXPECTED |  |
cls.seq_relationship.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/394 [00:00<?, ?it/s]

[transformers] BertForMaskedLM LOAD REPORT from: bert-large-uncased
Key                         | Status     |  |
----------------------------+------------+--+-
bert.pooler.dense.bias      | UNEXPECTED |  |
cls.seq_relationship.weight | UNEXPECTED |  |
bert.pooler.dense.weight    | UNEXPECTED |  |
cls.seq_relationship.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Models loaded.

In [ ]:
def prep_input(sentence, tokenizer):
    text = ["[CLS]"] + sentence.strip().split()
    if text[-1] != ".":
        text.append(".")
    text.append("[SEP]")

    tokenized = tokenizer.tokenize(" ".join(text))
    mask_positions = [i for i, t in enumerate(tokenized) if t == "[MASK]"]
    assert len(mask_positions) == 1, (sentence, tokenized)

    ids = tokenizer.convert_tokens_to_ids(tokenized)
    input_ids = torch.tensor([ids], device=device)
    return input_ids, mask_positions[0], tokenized


@torch.inference_mode()
def score_dataframe(df, model, tokenizer, topk=5):
    out = df.copy()
    target_probs, top_tokens, top_probs = [], [], []

    for _, row in out.iterrows():
        input_ids, mi, toks = prep_input(row["context"], tokenizer)
        logits = model(input_ids=input_ids).logits[0, mi]
        probs = torch.softmax(logits, dim=-1)

             target = row["target"]
        pieces = tokenizer.tokenize(target)
        assert len(pieces) == 1 and pieces[0] == target, (target, pieces)
        target_id = tokenizer.convert_tokens_to_ids(target)
        target_probs.append(probs[target_id].item())

        vals, inds = torch.topk(probs, k=topk)
        top_tokens.append(tokenizer.convert_ids_to_tokens(inds.tolist()))
        top_probs.append(vals.detach().cpu().tolist())

    out["target_prob"] = target_probs
    out["top_tokens"] = top_tokens
    out["top_probs"] = top_probs
    return out

In [ ]:
example = simp.query("item == '4' and cond == 'TA'").iloc[0]
_, mi, toks = prep_input(example.context, tok_large)
print(example.context)
print(toks)
print("mask index:", mi)

A robin is a [MASK]
['[CLS]', 'a', 'robin', 'is', 'a', '[MASK]', '.', '[SEP]']
mask index: 5

In [ ]:
simp_base  = score_dataframe(simp, bert_base,  tok_base,  topk=5)
simp_large = score_dataframe(simp, bert_large, tok_large, topk=5)
nat_base   = score_dataframe(nat,  bert_base,  tok_base,  topk=5)
nat_large  = score_dataframe(nat,  bert_large, tok_large, topk=5)

print("Scoring complete.")

Scoring complete.

In [ ]:
def simp_accuracy(scored, k):
    ta = scored[scored.cond == "TA"].copy()
    hits = [
        int(row.expected in row.top_tokens[:k])
        for _, row in ta.iterrows()
    ]
    return 100 * np.mean(hits), sum(hits), len(hits)

table11 = pd.DataFrame([
    ["BERT Base",  *simp_accuracy(simp_base, 1), *simp_accuracy(simp_base, 5)],
    ["BERT Large", *simp_accuracy(simp_large, 1), *simp_accuracy(simp_large, 5)],
], columns=["Model", "k1_pct", "k1_correct", "k1_n", "k5_pct", "k5_correct", "k5_n"])

display(table11)

print("Paper target:")
print("BERT Base : k=1 38.9%, k=5 100%")
print("BERT Large: k=1 44.4%, k=5 100%")

        Model     k1_pct  k1_correct  k1_n  k5_pct  k5_correct  k5_n
0   BERT Base  38.888889           7    18   100.0          18    18
1  BERT Large  44.444444           8    18   100.0          18    18

Paper target:
BERT Base : k=1 38.9%, k=5 100%
BERT Large: k=1 44.4%, k=5 100%

In [ ]:
def wide_probs(scored):
    return (
        scored.pivot(index="item", columns="cond", values="target_prob")
              .reset_index()
    )

def neg_sensitivity(scored, threshold=None):
    w = wide_probs(scored)

    aff_diff = w["TA"] - w["FA"]
    neg_diff = w["TN"] - w["FN"]

    if threshold is None:
        aff_hit = aff_diff > 0
        neg_hit = neg_diff > 0
    else:
        aff_hit = aff_diff > threshold
        neg_hit = neg_diff > threshold

    return {
        "Affirmative": 100 * aff_hit.mean(),
        "Negative": 100 * neg_hit.mean(),
        "Aff_correct": int(aff_hit.sum()),
        "Neg_correct": int(neg_hit.sum()),
        "n": len(w),
    }

table12 = pd.DataFrame([
    {"Model": "BERT Base",  **neg_sensitivity(simp_base)},
    {"Model": "BERT Large", **neg_sensitivity(simp_large)},
])
display(table12)

print("Paper target: both models = 100% affirmative, 0% negative")

table12_threshold = pd.DataFrame([
    {"Model": "BERT Base",  **neg_sensitivity(simp_base, threshold=.01)},
    {"Model": "BERT Large", **neg_sensitivity(simp_large, threshold=.01)},
])
display(table12_threshold)

        Model  Affirmative  Negative  Aff_correct  Neg_correct   n
0   BERT Base        100.0       0.0           18            0  18
1  BERT Large        100.0       0.0           18            0  18

Paper target: both models = 100% affirmative, 0% negative

        Model  Affirmative  Negative  Aff_correct  Neg_correct   n
0   BERT Base    94.444444       0.0           17            0  18
1  BERT Large   100.000000       0.0           18            0  18

In [ ]:
def nat_table14(scored):
    meta = scored[["item", "licensing"]].drop_duplicates("item")
    w = wide_probs(scored).merge(meta, on="item", how="left")

    result = {}
    for lic, label in [("Y", "NT"), ("N", "LN")]:
        d = w[w.licensing == lic]
        result[f"Aff. {label}"] = 100 * (d["TA"] > d["FA"]).mean()
        result[f"Neg. {label}"] = 100 * (d["TN"] > d["FN"]).mean()
    return result

table14 = pd.DataFrame([
    {"Model": "BERT Base",  **nat_table14(nat_base)},
    {"Model": "BERT Large", **nat_table14(nat_large)},
])
table14 = table14[["Model", "Aff. NT", "Neg. NT", "Aff. LN", "Neg. LN"]]
display(table14)

print("Paper target:")
print("BERT Base : 62.5, 87.5, 75.0, 0.0")
print("BERT Large: 75.0, 100.0, 75.0, 0.0")

        Model  Aff. NT  Neg. NT  Aff. LN  Neg. LN
0   BERT Base     62.5     87.5     75.0      0.0
1  BERT Large     75.0    100.0     75.0      0.0

Paper target:
BERT Base : 62.5, 87.5, 75.0, 0.0
BERT Large: 75.0, 100.0, 75.0, 0.0

In [ ]:
def show_context_predictions(scored, contexts):
    rows = []
    for context in contexts:
        match = scored[scored.context == context]
        if len(match):
            r = match.iloc[0]
            rows.append({
                "Context": context.replace("[MASK]", "____"),
                "BERT Large predictions": ", ".join(r.top_tokens[:5])
            })
    return pd.DataFrame(rows)

table13_contexts = [
    "A robin is a [MASK]",
    "A daisy is a [MASK]",
    "A hammer is a [MASK]",
    "A hammer is an [MASK]",
    "A robin is not a [MASK]",
    "A daisy is not a [MASK]",
    "A hammer is not a [MASK]",
    "A hammer is not an [MASK]",
]

table13 = show_context_predictions(simp_large, table13_contexts)
display(table13)

                   Context                         BERT Large predictions
0        A robin is a ____            bird, robin, person, hunter, pigeon
1        A daisy is a ____               daisy, rose, flower, berry, tree
2       A hammer is a ____             hammer, tool, weapon, nail, device
3      A hammer is an ____  object, instrument, axe, implement, explosive
4    A robin is not a ____                 robin, bird, penguin, man, fly
5    A daisy is not a ____              daisy, rose, flower, lily, cherry
6   A hammer is not a ____                hammer, weapon, tool, gun, rock
7  A hammer is not an ____      object, instrument, axe, animal, artifact

In [ ]:
table15_contexts = [
    "Most smokers find that quitting is very [MASK]",
    "Most smokers find that quitting isn't very [MASK]",
    "A fast food dinner on a first date is very [MASK]",
    "A fast food dinner on a first date isn't very [MASK]",
]

table15 = show_context_predictions(nat_large, table15_contexts)
display(table15)

,Context,BERT Large predictions
0,Most smokers find that quitting is very ____,"difficult, easy, effective, dangerous, hard"
1,Most smokers find that quitting isn't very ____,"effective, easy, attractive, difficult, succes..."
2,A fast food dinner on a first date is very ____,"good, nice, common, romantic, attractive"
3,A fast food dinner on a first date isn't very ...,"nice, good, romantic, appealing, exciting"

In [ ]:
def audit(scored):
    w = wide_probs(scored)
    w["TA>FA"] = w["TA"] > w["FA"]
    w["TN>FN"] = w["TN"] > w["FN"]
    w["TA-FA"] = w["TA"] - w["FA"]
    w["TN-FN"] = w["TN"] - w["FN"]
    return w

print("SIMP — BERT Base")
display(audit(simp_base))

print("SIMP — BERT Large")
display(audit(simp_large))

print("NAT — BERT Base")
display(audit(nat_base))

print("NAT — BERT Large")
display(audit(nat_large))

SIMP — BERT Base

cond,item,FA,FN,TA,TN,TA>FA,TN>FN,TA-FA,TN-FN
0,0,0.000454,0.282158,0.458702,7.007256e-05,True,False,0.458248,-0.282088
1,1,0.000294,0.372949,0.468620,7.392465e-05,True,False,0.468326,-0.372875
2,10,0.000044,0.007566,0.001668,6.144525e-04,True,False,0.001624,-0.006952
3,11,0.000435,0.012711,0.031981,3.654529e-04,True,False,0.031546,-0.012346
4,12,0.000578,0.177014,0.325408,4.986854e-04,True,False,0.324830,-0.176515
5,13,0.000004,0.022030,0.159117,4.140205e-06,True,False,0.159113,-0.022025
6,14,0.000095,0.238066,0.243470,1.194748e-04,True,False,0.243375,-0.237947
7,15,0.000016,0.103839,0.239107,4.882722e-06,True,False,0.239090,-0.103835
8,16,0.000005,0.002389,0.018337,3.913319e-07,True,False,0.018333,-0.002389
9,17,0.000120,0.013464,0.055227,1.260634e-05,True,False,0.055107,-0.013451
10,2,0.000369,0.009920,0.023876,6.548225e-04,True,False,0.023507,-0.009265
11,3,0.000738,0.612482,0.726103,8.571031e-05,True,False,0.725365,-0.612396
12,4,0.005804,0.096690,0.315533,2.640250e-03,True,False,0.309729,-0.094050
13,5,0.000021,0.535142,0.545084,1.468437e-05,True,False,0.545063,-0.535127
14,6,0.000042,0.927698,0.797508,4.915193e-05,True,False,0.797466,-0.927649
15,7,0.000095,0.542941,0.770262,2.896631e-04,True,False,0.770167,-0.542652
16,8,0.002200,0.303401,0.511275,1.144714e-03,True,False,0.509075,-0.302256
17,9,0.000197,0.072219,0.054946,6.657573e-04,True,False,0.054749,-0.071553

SIMP — BERT Large

cond,item,FA,FN,TA,TN,TA>FA,TN>FN,TA-FA,TN-FN
0,0,0.000055,0.539623,0.825476,0.000059,True,False,0.825421,-0.539563
1,1,0.000037,0.350676,0.597984,0.000058,True,False,0.597947,-0.350618
2,10,0.004687,0.015102,0.040064,0.003551,True,False,0.035377,-0.011551
3,11,0.000148,0.002650,0.041610,0.000089,True,False,0.041462,-0.002561
4,12,0.001689,0.095098,0.151806,0.002493,True,False,0.150117,-0.092605
5,13,0.000065,0.052297,0.500279,0.000082,True,False,0.500214,-0.052215
6,14,0.000148,0.066921,0.167242,0.000285,True,False,0.167094,-0.066637
7,15,0.000003,0.036160,0.029305,0.000007,True,False,0.029302,-0.036153
8,16,0.000004,0.008605,0.031087,0.000008,True,False,0.031083,-0.008597
9,17,0.000003,0.080459,0.217257,0.000033,True,False,0.217254,-0.080427
10,2,0.004742,0.085352,0.321126,0.002807,True,False,0.316385,-0.082545
11,3,0.000198,0.358430,0.491372,0.000052,True,False,0.491174,-0.358378
12,4,0.009511,0.087829,0.247797,0.002373,True,False,0.238286,-0.085456
13,5,0.000006,0.462497,0.580487,0.000002,True,False,0.580480,-0.462495
14,6,0.000183,0.774649,0.744313,0.000085,True,False,0.744129,-0.774564
15,7,0.000428,0.209651,0.522395,0.000156,True,False,0.521968,-0.209495
16,8,0.002698,0.058658,0.080181,0.001701,True,False,0.077483,-0.056958
17,9,0.001616,0.011399,0.086995,0.000451,True,False,0.085379,-0.010948

NAT — BERT Base

cond,item,FA,FN,TA,TN,TA>FA,TN>FN,TA-FA,TN-FN
0,0,0.038337,0.235215,0.109465,0.061657,True,False,0.071128,-0.173558
1,1,0.001107,0.014538,0.024116,0.039021,True,True,0.023009,0.024483
2,10,0.000092,0.159419,0.036679,0.010483,True,False,0.036587,-0.148936
3,11,0.000594,0.062366,0.002340,0.006485,True,False,0.001747,-0.055881
4,12,0.001750,0.009430,0.007406,0.000855,True,False,0.005655,-0.008575
5,13,0.000499,0.002088,0.000259,0.000066,False,False,-0.000240,-0.002023
6,14,0.002797,0.175657,0.245660,0.002639,True,False,0.242863,-0.173018
7,15,0.001028,0.015686,0.025153,0.000950,True,False,0.024126,-0.014736
8,2,0.000123,0.012109,0.000409,0.027839,True,True,0.000286,0.015730
9,3,0.023134,0.003575,0.004445,0.177035,False,True,-0.018689,0.173460
10,4,0.242264,0.014924,0.030158,0.080950,False,True,-0.212106,0.066026
11,5,0.049715,0.021924,0.218186,0.120850,True,True,0.168471,0.098926
12,6,0.000063,0.000039,0.000070,0.000250,True,True,0.000007,0.000211
13,7,0.011733,0.000084,0.003008,0.010720,False,True,-0.008724,0.010635
14,8,0.010563,0.015214,0.001097,0.010070,False,False,-0.009466,-0.005144
15,9,0.002555,0.065769,0.181133,0.025235,True,False,0.178578,-0.040534

NAT — BERT Large

cond,item,FA,FN,TA,TN,TA>FA,TN>FN,TA-FA,TN-FN
0,0,0.150971,0.147417,0.486117,0.384907,True,True,0.335145,0.237490
1,1,0.002638,0.019196,0.180071,0.060117,True,True,0.177433,0.040920
2,10,0.000127,0.221379,0.006098,0.001321,True,False,0.005971,-0.220057
3,11,0.000814,0.010763,0.004963,0.001637,True,False,0.004149,-0.009126
4,12,0.005743,0.090414,0.012966,0.000201,True,False,0.007224,-0.090212
5,13,0.000338,0.005825,0.000118,0.000141,False,False,-0.000221,-0.005684
6,14,0.001726,0.202487,0.532831,0.002655,True,False,0.531106,-0.199832
7,15,0.000551,0.095063,0.015363,0.002058,True,False,0.014812,-0.093004
8,2,0.000110,0.023491,0.001340,0.267007,True,True,0.001230,0.243516
9,3,0.001160,0.002768,0.008258,0.213558,True,True,0.007098,0.210790
10,4,0.274936,0.014287,0.022342,0.024761,False,True,-0.252594,0.010475
11,5,0.066778,0.038530,0.526481,0.117782,True,True,0.459703,0.079251
12,6,0.000029,0.000144,0.000219,0.000240,True,True,0.000190,0.000096
13,7,0.038933,0.000304,0.000188,0.105096,False,True,-0.038746,0.104793
14,8,0.027752,0.014733,0.006038,0.000875,False,False,-0.021714,-0.013858
15,9,0.000705,0.012015,0.341211,0.003446,True,False,0.340505,-0.008569

In [ ]:

BAL_FILENAME = "NEG-136-SIMP-BAL.tsv"
BAL_PATH = f"/content/{BAL_FILENAME}"

if not os.path.exists(BAL_PATH):
    from google.colab import files
    uploaded = files.upload()
    BAL_PATH = f"/content/{next(iter(uploaded))}"

bal_raw = pd.read_csv(BAL_PATH, sep="\t")
print("BAL path:", BAL_PATH)
print("BAL:", bal_raw.shape)
assert list(bal_raw.columns) == list(simp_raw.columns), bal_raw.columns
display(bal_raw.head())
display(pd.DataFrame({"as target_aff": bal_raw.target_aff.value_counts(),
                      "as target_neg": bal_raw.target_neg.value_counts()}))

Saving NEG-136-SIMP-BAL.tsv.tsv to NEG-136-SIMP-BAL.tsv.tsv
BAL path: /content/NEG-136-SIMP-BAL.tsv.tsv
BAL: (70, 5)

   item         context_aff             context_neg target_aff target_neg
0     1    A barn is (a|an)    A barn is not (a|an)   building      fruit
1     2  A banana is (a|an)  A banana is not (a|an)      fruit     flower
2     3   A hotel is (a|an)   A hotel is not (a|an)   building       fish
3     4    A moth is (a|an)    A moth is not (a|an)     insect       bird
4     5  A chisel is (a|an)  A chisel is not (a|an)       tool     flower

           as target_aff  as target_neg
bird                   7              7
building               7              7
fish                   7              7
flower                 7              7
fruit                  7              7
insect                 7              7
tool                   7              7
tree                   7              7
vegetable              7              7
vehicle                7              7

In [ ]:
bal = process_negsimp(BAL_PATH)

assert len(bal) == len(bal_raw) * 4
assert set(bal.cond) == {"TA","FN","FA","TN"}
for name, tok in [("base", tok_base), ("large", tok_large)]:
    bad = [t for t in sorted(bal.target.unique()) if tok.tokenize(t) != [t]]
    print(f"{name}: targets that are NOT single tokens -> {bad if bad else 'none'}")

display(bal.head(8))

base: targets that are NOT single tokens -> none
large: targets that are NOT single tokens -> none

  item cond                   context    target  expected
0    1   TA        A barn is a [MASK]  building  building
1    1   FN    A barn is not a [MASK]  building     fruit
2    1   FA        A barn is a [MASK]     fruit  building
3    1   TN    A barn is not a [MASK]     fruit     fruit
4    2   TA      A banana is a [MASK]     fruit     fruit
5    2   FN  A banana is not a [MASK]     fruit    flower
6    2   FA      A banana is a [MASK]    flower     fruit
7    2   TN  A banana is not a [MASK]    flower    flower

In [ ]:
example = bal.query("context == 'A robin is a [MASK]' and cond == 'TA'").iloc[0]
_, mi, toks = prep_input(example.context, tok_large)
print(example.context)
print(toks)
print("mask index:", mi)

A robin is a [MASK]
['[CLS]', 'a', 'robin', 'is', 'a', '[MASK]', '.', '[SEP]']
mask index: 5

In [ ]:
bal_base  = score_dataframe(bal, bert_base,  tok_base,  topk=5)
bal_large = score_dataframe(bal, bert_large, tok_large, topk=5)
print("Scoring complete (BAL).")

Scoring complete (BAL).

In [ ]:
table11_bal = pd.DataFrame([
    ["BERT Base",  *simp_accuracy(bal_base, 1),  *simp_accuracy(bal_base, 5)],
    ["BERT Large", *simp_accuracy(bal_large, 1), *simp_accuracy(bal_large, 5)],
], columns=["Model", "k1_pct", "k1_correct", "k1_n", "k5_pct", "k5_correct", "k5_n"])

print("Table 11 — NEG-136-SIMP-BAL")
display(table11_bal)

Table 11 — NEG-136-SIMP-BAL

        Model     k1_pct  k1_correct  k1_n     k5_pct  k5_correct  k5_n
0   BERT Base  38.571429          27    70  94.285714          66    70
1  BERT Large  55.714286          39    70  97.142857          68    70

In [ ]:
table12_bal = pd.DataFrame([
    {"Model": "BERT Base",  **neg_sensitivity(bal_base)},
    {"Model": "BERT Large", **neg_sensitivity(bal_large)},
])
print("Table 12 — NEG-136-SIMP-BAL")
display(table12_bal)


table12_bal_threshold = pd.DataFrame([
    {"Model": "BERT Base",  **neg_sensitivity(bal_base,  threshold=.01)},
    {"Model": "BERT Large", **neg_sensitivity(bal_large, threshold=.01)},
])
print("Table 12 (threshold 0.01) — NEG-136-SIMP-BAL")
display(table12_bal_threshold)

Table 12 — NEG-136-SIMP-BAL

        Model  Affirmative  Negative  Aff_correct  Neg_correct   n
0   BERT Base        100.0       0.0           70            0  70
1  BERT Large        100.0       0.0           70            0  70

Table 12 (threshold 0.01) — NEG-136-SIMP-BAL

        Model  Affirmative  Negative  Aff_correct  Neg_correct   n
0   BERT Base    95.714286       0.0           67            0  70
1  BERT Large    97.142857       0.0           68            0  70

In [ ]:
table13_bal = show_context_predictions(bal_large, table13_contexts)
print("Table 13 — NEG-136-SIMP-BAL (BERT Large)")
display(table13_bal)

Table 13 — NEG-136-SIMP-BAL (BERT Large)

                   Context                         BERT Large predictions
0        A robin is a ____            bird, robin, person, hunter, pigeon
1        A daisy is a ____               daisy, rose, flower, berry, tree
2       A hammer is a ____             hammer, tool, weapon, nail, device
3      A hammer is an ____  object, instrument, axe, implement, explosive
4    A robin is not a ____                 robin, bird, penguin, man, fly
5    A daisy is not a ____              daisy, rose, flower, lily, cherry
6   A hammer is not a ____                hammer, weapon, tool, gun, rock
7  A hammer is not an ____      object, instrument, axe, animal, artifact

Table 13 — NEG-136-SIMP-BAL, BERT Large, new items only (n=54)

,item,category,Affirmative context,Top-5 (affirmative),category in top-5,Negated context,Top-5 (negated),category STILL in top-5 after 'not'
0,1,building,A barn is a ____,"barn, building, house, farmhouse, farm",True,A barn is not a ____,"barn, house, building, farm, home",True
1,2,fruit,A banana is a ____,"banana, tree, fruit, vegetable, plant",True,A banana is not a ____,"banana, vegetable, tree, fruit, peach",True
2,4,insect,A moth is an ____,"insect, animal, object, ant, organism",True,A moth is not an ____,"animal, insect, object, ant, egg",True
3,5,tool,A chisel is a ____,"tool, hammer, knife, blade, weapon",True,A chisel is not a ____,"tool, knife, hammer, blade, weapon",True
4,6,vehicle,A train is a ____,"train, vehicle, locomotive, car, railroad",True,A train is not a ____,"train, car, boat, bus, ship",False
5,7,building,A church is a ____,"church, cathedral, parish, monastery, temple",False,A church is not a ____,"church, temple, cathedral, building, monastery",True
6,8,vegetable,A cabbage is a ____,"cabbage, vegetable, carrot, plant, potato",True,A cabbage is not a ____,"cabbage, vegetable, carrot, bean, dog",True
7,9,bird,A peacock is a ____,"peacock, bird, horse, parrot, butterfly",True,A peacock is not a ____,"peacock, bird, horse, butterfly, fox",True
8,10,building,A school is a ____,"school, college, building, community, structure",True,A school is not a ____,"school, church, university, home, place",False
9,13,tool,A drill is a ____,"drill, tool, machine, weapon, device",True,A drill is not a ____,"drill, tool, weapon, gun, bomb",True
10,14,flower,A tulip is a ____,"flower, plant, rose, tree, perennial",True,A tulip is not a ____,"flower, rose, plant, tree, butterfly",True
11,15,tree,A cedar is a ____,"tree, cedar, pine, rock, stone",True,A cedar is not a ____,"cedar, tree, pine, stone, rock",True
12,17,building,A hospital is a ____,"hospital, building, place, clinic, prison",True,A hospital is not a ____,"hospital, prison, place, home, clinic",False
13,20,vegetable,A radish is a ____,"vegetable, fruit, dessert, variety, cereal",True,A radish is not a ____,"vegetable, tree, cake, fruit, bowl",True
14,21,vehicle,A van is a ____,"car, vehicle, truck, van, bus",True,A van is not a ____,"car, van, vehicle, truck, bus",True
15,22,flower,A lily is a ____,"flower, lily, rose, plant, butterfly",True,A lily is not a ____,"rose, lily, flower, bird, butterfly",True
16,24,fruit,A grape is a ____,"grape, fruit, vine, wine, berry",True,A grape is not a ____,"grape, wine, vine, fruit, tree",True
17,26,tool,A trowel is a ____,"tool, knife, weapon, shovel, blade",True,A trowel is not a ____,"tool, knife, weapon, blade, shovel",True
18,28,bird,A hawk is a ____,"hawk, bird, hunter, predator, crow",True,A hawk is not a ____,"hawk, bird, falcon, fox, hunter",True
19,30,vegetable,A cauliflower is a ____,"vegetable, plant, flower, perennial, shrub",True,A cauliflower is not a ____,"vegetable, flower, plant, tree, fish",True
20,32,fish,A carp is a ____,"fish, carp, species, worm, swimmer",True,A carp is not a ____,"fish, carp, trout, frog, snake",True
21,33,tree,A maple is a ____,"tree, maple, plant, wood, shrub",True,A maple is not a ____,"maple, tree, leaf, pine, birch",True
22,34,tree,An elm is a ____,"tree, maple, shrub, elm, beech",True,An elm is not a ____,"tree, elm, pine, maple, oak",True
23,35,vehicle,A tractor is a ____,"vehicle, machine, tractor, car, truck",True,A tractor is not a ____,"tractor, car, truck, trailer, vehicle",True
24,37,vehicle,A helicopter is a ____,"helicopter, plane, vehicle, machine, ship",True,A helicopter is not a ____,"helicopter, plane, boat, ship, car",False
25,38,fruit,A lemon is a ____,"lemon, lime, berry, fruit, rose",True,A lemon is not a ____,"lemon, lime, rose, plum, peach",False
26,39,fish,A cod is a ____,"fish, lobster, crab, cod, boat",True,A cod is not a ____,"fish, cod, pig, boat, dog",True
27,40,vegetable,An onion is a ____,"vegetable, plant, carrot, potato, mushroom",True,An onion is not a ____,"vegetable, potato, fish, carrot, human",True
28,42,bird,An eagle is a ____,"bird, falcon, crow, raven, hawk",True,An eagle is not a ____,"bird, raven, falcon, crow, hawk",True
29,43,tree,A willow is a ____,"tree, willow, plant, shrub, leaf",True,A willow is not a ____,"willow, tree, reed, pine, witch",True
30,44,flower,An orchid is a ____,"plant, flower, tree, garden, weed",True,An orchid is not a ____,"plant, flower, tree, weed, bird",True
31,45,building,A castle is a ____,"castle, fortress, palace, building, fortification",True,A castle is not a ____,"castle, fortress, palace, city, home",False
32,46,tool,A wrench is a ____,"tool, hammer, lever, weapon, device",True,A wrench is not a ____,"hammer, weapon, gun, knife, tool",True
33,48,bird,An owl is a ____,"bird, crow, raven, human, person",True,An owl is not a ____,"bird, human, dog, vampire, wolf",True
34,49,fruit,A mango is a ____,"fruit, mango, tree, banana, berry",True,A mango is not a ____,"mango, peach, banana, fruit, tree",True
35,50,fish,A shark is a ____,"shark, fish, monster, whale, predator",True,A shark is not a ____,"shark, fish, whale, dolphin, monster",True
36,51,vehicle,A bus is a ____,"bus, car, vehicle, train, truck",True,A bus is not a ____,"bus, car, train, truck, vehicle",True
37,52,insect,A mantis is an ____,"insect, animal, organism, ant, eel",True,A mantis is not an ____,"insect, animal, ant, organism, adult",True
38,53,tool,A shovel is a ____,"shovel, tool, hammer, weapon, spade",True,A shovel is not a ____,"shovel, tool, weapon, hammer, knife",True
39,54,vegetable,A turnip is a ____,"vegetable, carrot, potato, tree, plant",True,A turnip is not a ____,"vegetable, tree, fish, carrot, potato",True
40,55,flower,A sunflower is a ____,"flower, plant, shrub, perennial, ##flower",True,A sunflower is not a ____,"flower, plant, seed, tree, rose",True
41,57,fish,A herring is a ____,"fish, herring, salmon, lobster, fisherman",True,A herring is not a ____,"fish, herring, salmon, boat, ship",True
42,58,insect,A beetle is an ____,"insect, animal, organism, object, ant",True,A beetle is not an ____,"insect, animal, object, ant, organism",True
43,59,insect,A ladybug is an ____,"insect, animal, owl, egg, elephant",True,A ladybug is not an ____,"animal, insect, object, angel, elephant",True
44,60,tree,A birch is a ____,"tree, birch, plant, wood, forest",True,A birch is not a ____,"birch, tree, pine, witch, rock",True
45,61,vegetable,A potato is a ____,"vegetable, potato, plant, cereal, food",True,A potato is not a ____,"potato, vegetable, plant, human, fish",True
46,63,insect,A wasp is an ____,"insect, animal, ant, organism, object",True,A wasp is not an ____,"insect, animal, ant, alien, egg",True
47,64,fruit,A pear is a ____,"pear, fruit, nut, tree, berry",True,A pear is not a ____,"pear, plum, nut, tree, peach",False
48,65,fruit,An apple is a ____,"tree, fruit, pear, nut, vegetable",True,An apple is not a ____,"tree, apple, human, lemon, man",False
49,66,tool,A screwdriver is a ____,"tool, screw, hammer, knife, device",True,A screwdriver is not a ____,"tool, screw, knife, gun, weapon",True
50,67,bird,A pigeon is a ____,"bird, pigeon, mammal, creature, parrot",True,A pigeon is not a ____,"pigeon, bird, dog, human, person",True
51,68,flower,A carnation is a ____,"flower, rose, plant, daisy, bouquet",True,A carnation is not a ____,"flower, rose, tree, diamond, daisy",True
52,69,fruit,A peach is a ____,"peach, plum, berry, lemon, rose",False,A peach is not a ____,"peach, plum, berry, lemon, flower",False
53,70,fish,A tuna is a ____,"fish, tuna, shark, crab, dolphin",True,A tuna is not a ____,"fish, tuna, shark, whale, salmon",True

BERT Large, all items: category in affirmative top-5 = 68/70; category still in top-5 after 'not' = 60/70
BERT Large, new items: category in affirmative top-5 = 52/54; category still in top-5 after 'not' = 45/54

Table 13 — NEG-136-SIMP-BAL, BERT Base, new items only (n=54)

,item,category,Affirmative context,Top-5 (affirmative),category in top-5,Negated context,Top-5 (negated),category STILL in top-5 after 'not'
0,1,building,A barn is a ____,"barn, building, farm, structure, house",True,A barn is not a ____,"barn, building, farm, house, structure",True
1,2,fruit,A banana is a ____,"banana, fruit, plant, tree, vegetable",True,A banana is not a ____,"banana, fruit, tree, vegetable, bananas",True
2,4,insect,A moth is an ____,"insect, animal, illusion, asteroid, ant",True,A moth is not an ____,"animal, insect, exception, organism, entity",True
3,5,tool,A chisel is a ____,"tool, weapon, hammer, blade, knife",True,A chisel is not a ____,"tool, hammer, weapon, knife, stone",True
4,6,vehicle,A train is a ____,"train, locomotive, car, thing, machine",False,A train is not a ____,"train, locomotive, car, vehicle, passenger",True
5,7,building,A church is a ____,"village, church, parish, cemetery, commune",False,A church is not a ____,"church, parish, community, sanctuary, religion",False
6,8,vegetable,A cabbage is a ____,"cabbage, vegetable, plant, potato, soup",True,A cabbage is not a ____,"cabbage, vegetable, potato, tomato, bean",True
7,9,bird,A peacock is a ____,"bird, peacock, horse, symbol, feather",True,A peacock is not a ____,"bird, peacock, horse, cat, butterfly",True
8,10,building,A school is a ____,"school, community, university, village, college",False,A school is not a ____,"school, community, college, university, village",False
9,13,tool,A drill is a ____,"drill, tool, weapon, device, machine",True,A drill is not a ____,"drill, tool, weapon, problem, test",True
10,14,flower,A tulip is a ____,"flower, plant, tree, shrub, grass",True,A tulip is not a ____,"flower, plant, tree, shrub, fruit",True
11,15,tree,A cedar is a ____,"tree, wood, shrub, timber, cedar",True,A cedar is not a ____,"tree, cedar, wood, timber, forest",True
12,17,building,A hospital is a ____,"hospital, doctor, profession, building, business",True,A hospital is not a ____,"hospital, prison, doctor, building, facility",True
13,20,vegetable,A radish is a ____,"noun, plant, perfume, vegetable, compound",True,A radish is not a ____,"drug, commodity, noun, product, mineral",False
14,21,vehicle,A van is a ____,"van, vehicle, car, truck, transport",True,A van is not a ____,"van, vehicle, car, truck, trailer",True
15,22,flower,A lily is a ____,"lily, flower, plant, symbol, rose",True,A lily is not a ____,"lily, flower, bird, rose, dove",True
16,24,fruit,A grape is a ____,"grape, wine, vine, variety, fruit",True,A grape is not a ____,"grape, wine, variety, vineyard, fruit",True
17,26,tool,A trowel is a ____,"tool, weapon, blade, knife, device",True,A trowel is not a ____,"tool, weapon, blade, knife, device",True
18,28,bird,A hawk is a ____,"bird, hawk, dog, falcon, snake",True,A hawk is not a ____,"hawk, bird, dog, predator, hunter",True
19,30,vegetable,A cauliflower is a ____,"plant, flower, ##flower, shrub, perennial",False,A cauliflower is not a ____,"flower, plant, weed, tree, perennial",False
20,32,fish,A carp is a ____,"carp, fish, bird, spear, snake",True,A carp is not a ____,"carp, fish, bird, dog, shark",True
21,33,tree,A maple is a ____,"tree, plant, maple, variety, wood",True,A maple is not a ____,"tree, maple, wood, plant, species",True
22,34,tree,An elm is a ____,"tree, shrub, plant, variety, ##ivar",True,An elm is not a ____,"tree, weed, plant, parent, hybrid",True
23,35,vehicle,A tractor is a ____,"tractor, vehicle, tool, truck, machine",True,A tractor is not a ____,"tractor, vehicle, truck, farmer, tool",True
24,37,vehicle,A helicopter is a ____,"helicopter, weapon, aircraft, vehicle, device",True,A helicopter is not a ____,"helicopter, weapon, vehicle, aircraft, plane",True
25,38,fruit,A lemon is a ____,"lemon, fruit, drink, cocktail, grape",True,A lemon is not a ____,"lemon, fruit, lime, grape, tree",True
26,39,fish,A cod is a ____,"cod, fish, crab, boat, vessel",True,A cod is not a ____,"cod, fish, ship, contract, band",True
27,40,vegetable,An onion is a ____,"onion, plant, tomato, vegetable, dish",True,An onion is not a ____,"onion, vegetable, tomato, flower, plant",True
28,42,bird,An eagle is a ____,"bird, symbol, seal, flag, falcon",True,An eagle is not a ____,"bird, symbol, threat, creature, species",True
29,43,tree,A willow is a ____,"willow, tree, plant, flower, shrub",True,A willow is not a ____,"willow, tree, plant, flower, shrub",True
30,44,flower,An orchid is a ____,"plant, orchid, flower, weed, shrub",True,An orchid is not a ____,"plant, flower, orchid, weed, species",True
31,45,building,A castle is a ____,"castle, building, structure, concept, fortification",True,A castle is not a ____,"castle, fortress, palace, building, fortification",True
32,46,tool,A wrench is a ____,"tool, weapon, firearm, device, gun",True,A wrench is not a ____,"tool, weapon, machine, device, hammer",True
33,48,bird,An owl is a ____,"bird, mammal, owl, raven, pigeon",True,An owl is not a ____,"bird, owl, mammal, dog, raven",True
34,49,fruit,A mango is a ____,"fruit, tree, mango, plant, dessert",True,A mango is not a ____,"mango, fruit, tree, bird, flower",True
35,50,fish,A shark is a ____,"shark, fish, predator, snake, concept",True,A shark is not a ____,"shark, fish, predator, monster, creature",True
36,51,vehicle,A bus is a ____,"bus, vehicle, car, driver, transport",True,A bus is not a ____,"bus, vehicle, car, coach, transport",True
37,52,insect,A mantis is an ____,"animal, insect, infection, illness, ant",True,A mantis is not an ____,"animal, infection, illness, insect, ant",True
38,53,tool,A shovel is a ____,"shovel, tool, weapon, spade, knife",True,A shovel is not a ____,"shovel, tool, weapon, knife, spade",True
39,54,vegetable,A turnip is a ____,"carrot, dog, vegetable, potato, fruit",True,A turnip is not a ____,"dog, vegetable, potato, carrot, cat",True
40,55,flower,A sunflower is a ____,"flower, plant, ##flower, tree, shrub",True,A sunflower is not a ____,"flower, plant, tree, ##flower, vegetable",True
41,57,fish,A herring is a ____,"fish, herring, fishery, crab, salmon",True,A herring is not a ____,"fish, herring, ship, vessel, salmon",True
42,58,insect,A beetle is an ____,"animal, example, insect, exception, object",True,A beetle is not an ____,"exception, animal, insect, entity, option",True
43,59,insect,A ladybug is an ____,"animal, insect, apple, adjective, object",True,A ladybug is not an ____,"animal, insect, exception, ant, adult",True
44,60,tree,A birch is a ____,"tree, shrub, wood, forest, plant",True,A birch is not a ____,"tree, birch, wood, forest, spruce",True
45,61,vegetable,A potato is a ____,"potato, vegetable, plant, cake, dessert",True,A potato is not a ____,"potato, vegetable, food, plant, meal",True
46,63,insect,A wasp is an ____,"insect, ant, animal, exception, organism",True,A wasp is not an ____,"insect, animal, exception, ant, organism",True
47,64,fruit,A pear is a ____,"pear, fruit, tree, flower, cactus",True,A pear is not a ____,"pear, tree, fruit, flower, cactus",True
48,65,fruit,An apple is a ____,"fruit, tree, apple, plant, flower",True,An apple is not a ____,"tree, fruit, apple, bird, flower",True
49,66,tool,A screwdriver is a ____,"tool, screw, knife, device, firearm",True,A screwdriver is not a ____,"tool, firearm, screw, weapon, device",True
50,67,bird,A pigeon is a ____,"pigeon, bird, lark, parrot, feather",True,A pigeon is not a ____,"pigeon, bird, dog, parrot, dove",True
51,68,flower,A carnation is a ____,"flower, plant, fruit, name, symbol",True,A carnation is not a ____,"flower, name, surname, car, symbol",True
52,69,fruit,A peach is a ____,"peach, fruit, flower, dessert, tree",True,A peach is not a ____,"peach, cherry, fruit, flower, tree",True
53,70,fish,A tuna is a ____,"tuna, fish, container, vessel, snack",True,A tuna is not a ____,"tuna, fish, shark, food, whale",True

BERT Base, all items: category in affirmative top-5 = 66/70; category still in top-5 after 'not' = 65/70
BERT Base, new items: category in affirmative top-5 = 50/54; category still in top-5 after 'not' = 50/54

In [ ]:
print("SIMP-BAL — BERT Base")
display(audit(bal_base))

print("SIMP-BAL — BERT Large")
display(audit(bal_large))

SIMP-BAL — BERT Base

cond,item,FA,FN,TA,TN,TA>FA,TN>FN,TA-FA,TN-FN
0,1,3.096038e-06,0.045827,0.223707,5.782852e-07,True,False,0.223704,-0.045826
1,10,3.585854e-04,0.001903,0.013419,7.779888e-05,True,False,0.013061,-0.001825
2,11,1.967524e-04,0.072219,0.054946,6.657573e-04,True,False,0.054749,-0.071553
3,12,4.208911e-05,0.927698,0.797508,4.915193e-05,True,False,0.797466,-0.927649
4,13,7.137485e-05,0.005584,0.057710,8.337881e-06,True,False,0.057639,-0.005575
5,14,1.677177e-05,0.563044,0.500486,2.880190e-05,True,False,0.500470,-0.563016
6,15,3.233316e-04,0.698534,0.836194,1.739339e-04,True,False,0.835871,-0.698360
7,16,2.939885e-04,0.372949,0.468620,7.392465e-05,True,False,0.468326,-0.372875
8,17,1.316093e-04,0.001202,0.014942,1.407258e-06,True,False,0.014810,-0.001200
9,18,9.493683e-05,0.542941,0.770262,2.896631e-04,True,False,0.770167,-0.542652
10,19,3.694899e-04,0.009920,0.023876,6.548225e-04,True,False,0.023507,-0.009265
11,2,1.135275e-03,0.030599,0.029849,1.134910e-03,True,False,0.028714,-0.029464
12,20,1.368072e-02,0.020807,0.019873,3.095311e-03,True,False,0.006192,-0.017712
13,21,3.972108e-05,0.152167,0.287324,6.108770e-05,True,False,0.287284,-0.152106
14,22,1.539557e-04,0.062547,0.287754,1.137896e-04,True,False,0.287600,-0.062433
15,23,2.149893e-05,0.535142,0.545084,1.468437e-05,True,False,0.545063,-0.535127
16,24,3.444896e-03,0.008690,0.019361,3.172469e-03,True,False,0.015916,-0.005517
17,25,7.375481e-04,0.612482,0.726103,8.571031e-05,True,False,0.725365,-0.612396
18,26,7.007181e-05,0.512814,0.360969,4.081568e-05,True,False,0.360899,-0.512773
19,27,5.776042e-04,0.177014,0.325408,4.986854e-04,True,False,0.324830,-0.176515
20,28,7.902379e-06,0.251473,0.507206,3.552219e-06,True,False,0.507199,-0.251469
21,29,4.441910e-05,0.007566,0.001668,6.144525e-04,True,False,0.001624,-0.006952
22,3,4.752328e-06,0.002389,0.018337,3.913319e-07,True,False,0.018333,-0.002389
23,30,2.557407e-04,0.018282,0.014723,2.288324e-04,True,False,0.014467,-0.018053
24,31,9.490212e-05,0.238066,0.243470,1.194748e-04,True,False,0.243375,-0.237947
25,32,2.138126e-06,0.340896,0.242032,3.646091e-06,True,False,0.242030,-0.340892
26,33,7.215938e-04,0.593156,0.622384,5.170745e-03,True,False,0.621662,-0.587985
27,34,6.572077e-06,0.653210,0.542336,1.043535e-05,True,False,0.542329,-0.653199
28,35,1.915911e-06,0.026041,0.058578,9.306884e-06,True,False,0.058576,-0.026032
29,36,2.200209e-03,0.303401,0.511275,1.144714e-03,True,False,0.509075,-0.302256
30,37,6.633515e-05,0.012765,0.023823,2.055701e-05,True,False,0.023757,-0.012744
31,38,3.119863e-04,0.007984,0.016484,4.197220e-04,True,False,0.016172,-0.007565
32,39,5.012562e-04,0.014173,0.080871,1.863600e-04,True,False,0.080369,-0.013987
33,4,1.723101e-02,0.115405,0.168546,5.156281e-02,True,False,0.151315,-0.063842
34,40,1.316642e-04,0.096830,0.047267,3.069415e-04,True,False,0.047135,-0.096523
35,41,1.624173e-05,0.103839,0.239107,4.882722e-06,True,False,0.239090,-0.103835
36,42,1.557055e-05,0.759973,0.608354,1.005994e-05,True,False,0.608339,-0.759963
37,43,6.438034e-05,0.270179,0.244778,2.620932e-05,True,False,0.244713,-0.270152
38,44,4.090154e-04,0.147051,0.089978,5.635579e-04,True,False,0.089569,-0.146487
39,45,4.364689e-04,0.014139,0.058111,5.615915e-05,True,False,0.057674,-0.014083
40,46,1.494913e-04,0.410881,0.323330,2.226472e-04,True,False,0.323180,-0.410659
41,47,5.804135e-03,0.096690,0.315533,2.640250e-03,True,False,0.309729,-0.094050
42,48,4.184943e-04,0.797256,0.841009,4.285723e-05,True,False,0.840591,-0.797213
43,49,2.694027e-03,0.124981,0.429834,3.315644e-02,True,False,0.427140,-0.091825
44,5,3.886717e-05,0.623186,0.619467,2.959350e-05,True,False,0.619428,-0.623156
45,50,2.209339e-04,0.161986,0.109167,1.443443e-04,True,False,0.108946,-0.161842
46,51,3.818682e-05,0.038466,0.055385,5.764156e-06,True,False,0.055347,-0.038460
47,52,4.189890e-03,0.029721,0.143234,1.069352e-03,True,False,0.139044,-0.028651
48,53,4.679143e-07,0.136384,0.271891,1.015610e-06,True,False,0.271891,-0.136383
49,54,4.397991e-04,0.074541,0.030062,4.129184e-04,True,False,0.029622,-0.074128
50,55,1.949818e-02,0.626897,0.691479,1.037625e-02,True,False,0.671981,-0.616521
51,56,4.542578e-04,0.282158,0.458702,7.007256e-05,True,False,0.458248,-0.282088
52,57,5.778897e-04,0.525440,0.561805,1.423233e-03,True,False,0.561227,-0.524017
53,58,1.391719e-04,0.056767,0.045481,3.090873e-04,True,False,0.045342,-0.056458
54,59,4.472582e-03,0.044957,0.126981,2.695434e-03,True,False,0.122508,-0.042262
55,6,3.058403e-05,0.017833,0.011670,1.739755e-05,True,False,0.011639,-0.017816
56,60,1.604329e-05,0.653990,0.802506,4.426516e-05,True,False,0.802490,-0.653945
57,61,2.186161e-03,0.057409,0.042298,2.063873e-03,True,False,0.040112,-0.055345
58,62,1.199932e-04,0.013464,0.055227,1.260634e-05,True,False,0.055107,-0.013451
59,63,6.627414e-04,0.420898,0.609445,8.262045e-04,True,False,0.608782,-0.420072
60,64,5.465380e-04,0.096477,0.301354,3.186510e-04,True,False,0.300807,-0.096159
61,65,5.414155e-04,0.119243,0.294496,7.752595e-04,True,False,0.293954,-0.118468
62,66,4.483982e-06,0.462445,0.541685,6.302415e-06,True,False,0.541681,-0.462439
63,67,6.276522e-06,0.293035,0.094355,2.309218e-05,True,False,0.094349,-0.293012
64,68,3.670729e-02,0.080532,0.315480,1.067516e-02,True,False,0.278772,-0.069857
65,69,5.899711e-05,0.007211,0.083704,1.857421e-05,True,False,0.083645,-0.007193
66,7,6.986086e-06,0.014028,0.004867,3.052241e-05,True,False,0.004860,-0.013998
67,70,1.624417e-05,0.243371,0.186150,6.481146e-06,True,False,0.186134,-0.243364
68,8,3.339333e-06,0.035227,0.069760,1.085977e-05,True,False,0.069757,-0.035216
69,9,3.940645e-04,0.684502,0.638558,6.158651e-05,True,False,0.638164,-0.684441

SIMP-BAL — BERT Large

cond,item,FA,FN,TA,TN,TA>FA,TN>FN,TA-FA,TN-FN
0,1,1.155942e-06,0.018654,0.164568,0.000001,True,False,0.164566,-0.018653
1,10,3.383576e-05,0.010343,0.028303,0.000189,True,False,0.028269,-0.010153
2,11,1.615921e-03,0.011399,0.086995,0.000451,True,False,0.085379,-0.010948
3,12,1.830772e-04,0.774649,0.744313,0.000085,True,False,0.744129,-0.774564
4,13,1.557600e-04,0.013861,0.169594,0.000260,True,False,0.169438,-0.013601
5,14,5.528994e-05,0.630374,0.697342,0.000020,True,False,0.697287,-0.630355
6,15,8.261104e-04,0.090728,0.495718,0.000145,True,False,0.494892,-0.090583
7,16,3.734195e-05,0.350676,0.597984,0.000058,True,False,0.597947,-0.350618
8,17,4.836871e-05,0.005710,0.023273,0.000079,True,False,0.023224,-0.005631
9,18,4.276712e-04,0.209651,0.522395,0.000156,True,False,0.521968,-0.209495
10,19,4.741871e-03,0.085352,0.321126,0.002807,True,False,0.316385,-0.082545
11,2,9.315600e-03,0.008659,0.056814,0.003568,True,False,0.047498,-0.005091
12,20,1.386625e-02,0.068871,0.242960,0.005166,True,False,0.229094,-0.063705
13,21,8.594950e-05,0.075974,0.241186,0.000045,True,False,0.241100,-0.075930
14,22,1.505970e-04,0.155954,0.385877,0.000046,True,False,0.385727,-0.155908
15,23,6.238372e-06,0.462497,0.580487,0.000002,True,False,0.580480,-0.462495
16,24,1.198740e-02,0.038549,0.173541,0.022095,True,False,0.161553,-0.016454
17,25,1.984505e-04,0.358430,0.491372,0.000052,True,False,0.491174,-0.358378
18,26,1.631913e-04,0.254130,0.548411,0.000297,True,False,0.548248,-0.253833
19,27,1.688860e-03,0.095098,0.151806,0.002493,True,False,0.150117,-0.092605
20,28,9.941931e-06,0.117720,0.199188,0.000004,True,False,0.199178,-0.117716
21,29,4.686711e-03,0.015102,0.040064,0.003551,True,False,0.035377,-0.011551
22,3,4.108865e-06,0.008605,0.031087,0.000008,True,False,0.031083,-0.008597
23,30,2.112795e-06,0.171025,0.273992,0.000014,True,False,0.273990,-0.171011
24,31,1.478665e-04,0.066921,0.167242,0.000285,True,False,0.167094,-0.066637
25,32,3.179327e-06,0.448068,0.871626,0.000019,True,False,0.871623,-0.448050
26,33,5.886293e-03,0.153351,0.700857,0.002860,True,False,0.694971,-0.150491
27,34,3.780473e-06,0.761643,0.656618,0.000020,True,False,0.656615,-0.761623
28,35,4.101967e-05,0.021840,0.381426,0.000137,True,False,0.381385,-0.021703
29,36,2.698447e-03,0.058658,0.080181,0.001701,True,False,0.077483,-0.056958
30,37,8.971227e-05,0.004236,0.047056,0.000087,True,False,0.046966,-0.004149
31,38,7.774672e-04,0.001003,0.007225,0.000307,True,False,0.006447,-0.000696
32,39,2.429070e-05,0.286416,0.705835,0.000145,True,False,0.705810,-0.286271
33,4,5.333875e-02,0.311898,0.346798,0.111222,True,False,0.293459,-0.200676
34,40,4.901357e-04,0.125929,0.377483,0.000688,True,False,0.376992,-0.125241
35,41,2.992286e-06,0.036160,0.029305,0.000007,True,False,0.029302,-0.036153
36,42,2.534262e-05,0.390620,0.421886,0.000041,True,False,0.421861,-0.390580
37,43,4.807106e-04,0.219902,0.602483,0.000050,True,False,0.602002,-0.219852
38,44,2.001265e-04,0.222404,0.109919,0.003773,True,False,0.109719,-0.218632
39,45,6.063678e-06,0.004950,0.020673,0.000033,True,False,0.020667,-0.004917
40,46,5.821977e-06,0.061282,0.226716,0.000028,True,False,0.226710,-0.061254
41,47,9.511339e-03,0.087829,0.247797,0.002373,True,False,0.238286,-0.085456
42,48,7.329990e-05,0.353895,0.345756,0.000062,True,False,0.345683,-0.353833
43,49,2.161697e-03,0.017252,0.217587,0.001141,True,False,0.215426,-0.016112
44,5,1.215696e-05,0.385658,0.652295,0.000109,True,False,0.652283,-0.385549
45,50,2.767299e-05,0.086271,0.049733,0.000017,True,False,0.049705,-0.086253
46,51,2.578879e-05,0.017085,0.102487,0.000038,True,False,0.102461,-0.017047
47,52,1.285982e-03,0.553623,0.937320,0.008150,True,False,0.936034,-0.545473
48,53,1.837993e-05,0.053064,0.326184,0.000006,True,False,0.326166,-0.053058
49,54,5.458232e-06,0.166147,0.545516,0.000028,True,False,0.545510,-0.166119
50,55,1.531387e-01,0.593272,0.571005,0.149622,True,False,0.417866,-0.443649
51,56,5.491714e-05,0.539623,0.825476,0.000059,True,False,0.825421,-0.539563
52,57,3.903012e-06,0.382697,0.454029,0.000044,True,False,0.454025,-0.382653
53,58,1.836060e-03,0.473546,0.732155,0.001098,True,False,0.730319,-0.472448
54,59,3.027936e-03,0.076305,0.391866,0.000902,True,False,0.388838,-0.075403
55,6,1.105236e-05,0.017524,0.087568,0.000017,True,False,0.087557,-0.017506
56,60,8.893428e-05,0.268365,0.822712,0.000135,True,False,0.822623,-0.268230
57,61,1.787818e-02,0.105636,0.172383,0.001890,True,False,0.154505,-0.103746
58,62,2.588838e-06,0.080459,0.217257,0.000033,True,False,0.217254,-0.080427
59,63,3.784453e-03,0.685378,0.747336,0.003799,True,False,0.743551,-0.681579
60,64,1.786428e-02,0.014666,0.109676,0.002004,True,False,0.091812,-0.012663
61,65,8.826244e-04,0.013270,0.047198,0.000187,True,False,0.046316,-0.013083
62,66,6.542071e-07,0.271068,0.619763,0.000022,True,False,0.619762,-0.271045
63,67,1.247796e-04,0.225735,0.470552,0.000078,True,False,0.470427,-0.225657
64,68,2.809986e-03,0.468953,0.914537,0.001356,True,False,0.911727,-0.467597
65,69,2.601738e-05,0.000734,0.002530,0.000014,True,False,0.002504,-0.000720
66,7,1.250606e-05,0.036815,0.032786,0.000072,True,False,0.032773,-0.036744
67,70,3.717577e-06,0.320757,0.630327,0.000019,True,False,0.630323,-0.320739
68,8,1.494673e-05,0.023530,0.182008,0.000001,True,False,0.181993,-0.023529
69,9,9.386414e-05,0.058078,0.211983,0.000024,True,False,0.211890,-0.058054

In [ ]:
cmp11 = pd.concat([table11.assign(Dataset="NEG-136-SIMP"),
                   table11_bal.assign(Dataset="NEG-136-SIMP-BAL")])
cmp11 = cmp11[["Dataset", "Model", "k1_pct", "k1_correct", "k1_n", "k5_pct", "k5_correct", "k5_n"]]
print("Table 11 comparison")
display(cmp11.reset_index(drop=True))

cmp12 = pd.concat([table12.assign(Dataset="NEG-136-SIMP", Threshold="none"),
                   table12_threshold.assign(Dataset="NEG-136-SIMP", Threshold="0.01"),
                   table12_bal.assign(Dataset="NEG-136-SIMP-BAL", Threshold="none"),
                   table12_bal_threshold.assign(Dataset="NEG-136-SIMP-BAL", Threshold="0.01")])
cmp12 = cmp12[["Dataset", "Threshold", "Model", "Affirmative", "Negative", "Aff_correct", "Neg_correct", "n"]]
print("Table 12 comparison")
display(cmp12.reset_index(drop=True))

Table 11 comparison

,Dataset,Model,k1_pct,k1_correct,k1_n,k5_pct,k5_correct,k5_n
0,NEG-136-SIMP,BERT Base,38.888889,7,18,100.000000,18,18
1,NEG-136-SIMP,BERT Large,44.444444,8,18,100.000000,18,18
2,NEG-136-SIMP-BAL,BERT Base,38.571429,27,70,94.285714,66,70
3,NEG-136-SIMP-BAL,BERT Large,55.714286,39,70,97.142857,68,70

Table 12 comparison

,Dataset,Threshold,Model,Affirmative,Negative,Aff_correct,Neg_correct,n
0,NEG-136-SIMP,none,BERT Base,100.000000,0.0,18,0,18
1,NEG-136-SIMP,none,BERT Large,100.000000,0.0,18,0,18
2,NEG-136-SIMP,0.01,BERT Base,94.444444,0.0,17,0,18
3,NEG-136-SIMP,0.01,BERT Large,100.000000,0.0,18,0,18
4,NEG-136-SIMP-BAL,none,BERT Base,100.000000,0.0,70,0,70
5,NEG-136-SIMP-BAL,none,BERT Large,100.000000,0.0,70,0,70
6,NEG-136-SIMP-BAL,0.01,BERT Base,95.714286,0.0,67,0,70
7,NEG-136-SIMP-BAL,0.01,BERT Large,97.142857,0.0,68,0,70

In [ ]:
def per_category(scored, raw, model_name):
    w = wide_probs(scored)
    w["category"] = w["item"].map(dict(zip(raw["item"].astype(str), raw["target_aff"])))
    ta = scored[scored.cond == "TA"].copy()
    ta["k1"] = [row.expected in row.top_tokens[:1] for _, row in ta.iterrows()]
    ta["k5"] = [row.expected in row.top_tokens[:5] for _, row in ta.iterrows()]
    w = w.merge(ta[["item", "k1", "k5"]], on="item")
    g = w.groupby("category")[["TA", "FA", "TN", "FN", "k1", "k5"]].apply(lambda d: pd.Series({
        "n": len(d),
        "k1_pct": 100 * d.k1.mean(),
        "k5_pct": 100 * d.k5.mean(),
        "Affirmative": 100 * (d.TA > d.FA).mean(),
        "Negative": 100 * (d.TN > d.FN).mean(),
    }))
    return g.reset_index().assign(Model=model_name)

per_cat_bal = pd.concat([per_category(bal_base, bal_raw, "BERT Base"),
                         per_category(bal_large, bal_raw, "BERT Large")])
display(per_cat_bal[["Model", "category", "n", "k1_pct", "k5_pct", "Affirmative", "Negative"]].reset_index(drop=True))

         Model   category    n      k1_pct      k5_pct  Affirmative  Negative
0    BERT Base       bird  7.0   71.428571  100.000000        100.0       0.0
1    BERT Base   building  7.0    0.000000   71.428571        100.0       0.0
2    BERT Base       fish  7.0   42.857143  100.000000        100.0       0.0
3    BERT Base     flower  7.0   57.142857  100.000000        100.0       0.0
4    BERT Base      fruit  7.0   28.571429  100.000000        100.0       0.0
5    BERT Base     insect  7.0   42.857143  100.000000        100.0       0.0
6    BERT Base       tool  7.0   57.142857  100.000000        100.0       0.0
7    BERT Base       tree  7.0   85.714286  100.000000        100.0       0.0
8    BERT Base  vegetable  7.0    0.000000   85.714286        100.0       0.0
9    BERT Base    vehicle  7.0    0.000000   85.714286        100.0       0.0
10  BERT Large       bird  7.0   71.428571  100.000000        100.0       0.0
11  BERT Large   building  7.0    0.000000   85.714286        100.0       0.0
12  BERT Large       fish  7.0   85.714286  100.000000        100.0       0.0
13  BERT Large     flower  7.0   57.142857  100.000000        100.0       0.0
14  BERT Large      fruit  7.0   14.285714   85.714286        100.0       0.0
15  BERT Large     insect  7.0   85.714286  100.000000        100.0       0.0
16  BERT Large       tool  7.0   57.142857  100.000000        100.0       0.0
17  BERT Large       tree  7.0  100.000000  100.000000        100.0       0.0
18  BERT Large  vegetable  7.0   71.428571  100.000000        100.0       0.0
19  BERT Large    vehicle  7.0   14.285714  100.000000        100.0       0.0